### ISSUE TITLE
Tube priorities

### ISSUE THREAD

**Issue by nutrun** [beanstalkd/beanstalkd#107]
Ever considered having a priority field on tubes, same as in jobs? This would be useful for grouping jobs that don't run until a group of jobs they depend on has been completed. #feature

**Comment by JensRantil** [comment]
@nutrun I don't fully understand your description. If both tubes and jobs had a priority, which one would take precendence over the other? The tube?

AFAIK, couldn't you simply work around this by having a higher priority for all jobs in one tube, and all jobs in another tube would have lower priority?

**Comment by kr** [comment]
The word "priority" in beanstalkd doesn't create dependencies between jobs, and doesn't have anything to do with when a job finishes. It has only to do with scheduling the order in which jobs begin.

The current rule for which job to run next involves only the jobs themselves: there is a total order defined over all jobs (based [first on priority, then on job id](https://github.com/kr/beanstalkd/blob/d2922bd4/job.c#L157-L164) as a tiebreaker). Of the subset of jobs that are [eligible to run](https://github.com/kr/beanstalkd/blob/d2922bd4/prot.c#L394-L416) at any given moment, we run the lowest one from that total order.

So yeah, this is a good discussion. The idea of giving each tube a "priority" seems interesting, but there are a lot of questions to answer. What concrete problem are we trying to solve? How would it interact with job priorities—how would we change the existing rule to accommodate tube priorities, and why?

**Comment by nutrun** [comment]
The problem I wanted addressed when I suggested the feature was the ability to block a group of jobs from running until another group of jobs has finished running, i.e job dependencies. It came up while writing https://github.com/nutrun/glow and we solved it with https://github.com/nutrun/glow#tube-dependencies which we found clunky, hence the suggestion to do it in beanstalkd. We used beanstalkd via glow for multi-stage batch processing, where some stages had to complete before the next stage executed. 

Maybe overloading the term "priority" isn't the right thing. What I had in mind was the ability to block all jobs in tube X from running until all jobs in tube Y have completed.

**Comment by ysmolsky** [comment]
I still do not understand what is meant by "the ability to block a group of jobs from running until another group of jobs has finished running, i.e job dependencies" and how it is related to tubes priorities. Most likely this to be closed soon.

**Comment by ysmolsky** [comment]
I’m closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
