### ISSUE TITLE
Allow deletion of jobs from other connections

### ISSUE THREAD

**Issue by Dachande663** [beanstalkd/beanstalkd#109]
There are cases where it would be useful to delete a job from a connection other than the one that reserved it, for instance in a manager/worker type situation. Currently, only the original reserver can delete a job.

Could the delete command be updated to allow cross-connection deletions or a separate force_delete(?) command introduced to make the act explicit to avoid accidentally deleting other jobs?

**Comment by ysmolsky** [comment]
It goes against the protocol. To delete the job you need to reserver it first. So it cannot be fixed by allowing to delete any job. This could be fixed by allowing to reserver any job by id. Closing in favor of #310
