### ISSUE TITLE
stateless connections

### ISSUE THREAD

**Issue by pda** [beanstalkd/beanstalkd#11]
Stateful connections cause problems, especially when processing long-running jobs
or connecting over long distances or complicated network topologies. We can solve
these problems by learning from HTTP: prefer (rather, require) stateless, disposable,
short-lived connections.

However, statelessness poses challenges, especially with efficiency. For example,
repeating the tube name for every put command would use more bandwidth than
the current protocol. So this is a tradeoff.

The current beanstalkd protocol is highly stateful and its design pervasively assumes
that state is available. It uses this where possible to be more efficient.

We should reevaluate whether the current statefulness of the protocol is the best tradeoff.

Original post follows.

---

Currently when a client disconnects while it has a reserved job, that job is instantly released onto the front of the queue, without respect of its remaining TTR.

This means that:
- A worker executing long jobs cannot disconnect/reconnect to beanstalkd during execution.  Perhaps that would make it too hard to track which client owns which job reservation though...
- A job that causes a worker to crash constantly hogs the front of the queue, blocking subsequent jobs from coming through.

Perhaps auto-release due to disconnect should at least release onto the end of the queue, at a lower priority, or with a delay..?

**Comment by ysmolsky** [comment]
The answer by @kr sums it rather well. Also I second this post https://xph.us/2010/05/02/how-to-handle-job-failures.html. From my experience it is possible to handle errors or crashes gracefully. I do not know why this issue was kept open for so long since we are not going to solve it foreseeable future. I will hold it open, but mark as unplanned.
