### ISSUE TITLE
how should we know if the beastalkd service is in drain mode?

### ISSUE THREAD

**Issue by JerryKwan** [beanstalkd/beanstalkd#145]
is there any way we can tell the beanstalkd service is  in drain mode?
when we try to put a new job, may be we can tell the beanstalkd service is in drain mode through the return result. if we can add some info in stats command?then we can tell the drain mode at any time without try to input some job?

**Comment by chrisminett** [comment]
There's a commit for this that appears to be orphaned. Any chance of seeing this put into a release?

**Comment by JensRantil** [comment]
Typo in issue title.

**Comment by ysmolsky** [comment]
> There's a commit for this that appears to be orphaned. Any chance of seeing this put into a release?

@chrisminett what is the commit?

**Comment by chrisminett** [comment]
@ysmolsky no idea, that was 4 years ago!

At a guess it was probably something to do with #219 which has now been replaced by #307 , to which you're assigned. The change to the `stats` command achieved by that PR looks good for our use case - being able to tell if a server is draining without having to put a job.

**Comment by ysmolsky** [comment]
@chrisminett thanks, this helps me. I will look into that PR and come with my own, better, fix, hopefully.
