### ISSUE TITLE
segfault in connsoonestjob at conn.c:166

### ISSUE THREAD

**Issue by kr** [beanstalkd/beanstalkd#160]
Reported by @aqibsm in #119:

> I am facing the same issue on CentOS 6.3 Beanstalkd 1.8
> 
> Dec 13 13:02:35 vm7-d2 kernel: beanstalkd[8701] general protection ip:40200a sp:7fff6c65fa10 error:0 in beanstalkd[400000+11000]
> Dec 13 14:59:17 vm7-d2 kernel: beanstalkd[9993] general protection ip:40200a sp:7fff6c6f2fc0 error:0 in beanstalkd[400000+11000]
> 
> Beanstalkd 1.4 was running fine without any issue so reverting back 1.4

**Comment by JensRantil** [comment]
@kr Did you have any idea on this?

**Comment by thorro** [comment]
We're getting the same error on v1.10:

`Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004021c0 in connsoonestjob (c=0x64d0f40) at conn.c:166
166	            if (j->r.deadline_at <= (soonest ? : j)->r.deadline_at) soonest = j;`

Anyone found the cause of this? @kr ?

**Comment by jhammer** [comment]
We have just hit this, as well:

Apr  8 17:46:37 db01 kernel: [56880694.274429] traps: beanstalkd[1048] general protection ip:40241c sp:7ffd78a06a20 error:0 in beanstalkd[400000+e000]

**Comment by ysmolsky** [comment]
@jhammer, what version do you run? Can you produce the stack trace?

**Comment by jhammer** [comment]
@ysmolsky version 1.9. Sorry, I do not have the stack trace. Seem pretty rare in our case. Only hit the issue once after literally years of uptime.

**Comment by thorro** [comment]
There are a few stacktraces lying around here. We hit it once in a while. Lately not much, since we've moved majority of our workload to another queue manager. It seems the number of crashes correlate with workload.

**Comment by ysmolsky** [comment]
@thorro could you paste those stacktraces here? Did you move to another queue manager because beanstalkd failed to handle the load?

**Comment by thorro** [comment]
@ysmolsky we moved mainly because of the crashes. Link to bt:

https://github.com/beanstalkd/beanstalkd/issues/328#issuecomment-345387502

Also, because sometimes binlog files got out of hand. Meaning, when there were a lot of jobs, binglog size grew, which is normal, but when the jobs got processed and deleted, binlog size stayed the same, it didn't shrink. But that's another issue.

**Comment by ysmolsky** [comment]
Without a core dump it's next to impossible to fix this kind of error. If anyone can share core dump (that will contain everything that is inside of beanstalkd), I would be glad to look at and try to fix this. 
[How to get a core dump for a segfault on Linux](https://jvns.ca/blog/2018/04/28/debugging-a-segfault-on-linux/)
