### ISSUE TITLE
SPYD to the rescue

### ISSUE THREAD

**Issue by rcapozzi** [beanstalkd/beanstalkd#173]
Could beanstalkd be extended to support SPYD listeners? The server needs to know SPYD protocol, and it need to handle blocking and, of course, the client must know SPDY too. In other words, a lighter JMS like messaging approach.

I have been wrestling with a project that could benefit from a highly concurrent approach. The benefits of lots of threads over lots of processed is hard to quantify. One big win for processes is that they run across a compute cluster. The BI tool knows about sockets and http requests, however it does not know JMS. Therefor I ask the question.

Don't be weighted down with my exact use case. I'd be happy to connect my SPYD client to a beanstalkd server just to avoid protocol issues.

**Comment by JensRantil** [comment]
What is the reason for introducing SPDY? To be able to mux the traffic? I suggest to keep things simple and do connection pooling in the client.

**Comment by ysmolsky** [comment]
SPDY was deprecated: https://en.wikipedia.org/wiki/SPDY
