### ISSUE TITLE
At high tube IO rates, beanstalk progressively becomes more latent

### ISSUE THREAD

**Issue by bmhatfield** [beanstalkd/beanstalkd#184]
For an example of what I am referring to, see the 'before we restarted beanstalkd' and 'after' graph attached below:

![screen shot 2013-05-29 at 11 45 40 pm](https://f.cloud.github.com/assets/1119967/583132/fa9a009a-c8dc-11e2-9159-b214bf38f67f.png)

My general theory is that we are experiencing memory fragmentation within the beanstalk process, but I am not sure how to prove that. I am thinking that it might be related to this issue: https://github.com/kr/beanstalkd/issues/54 - but I am not sure.

What kind of information can I gather you to be useful? It takes days of production traffic to get to the point where it starts grinding itself to a halt, and I can't seem to strace once it has ground down (it segfaults when I try to connect to the pid, every time) - thoughts?

**Comment by abliss** [comment]
I also see my beanstalkd (v1.18) segfault when I attach strace under high load. Did anyone figure out why that might happen?

**Comment by silviucpp** [comment]
This most probably can be closed. Might be duplicated with #200

**Comment by ysmolsky** [comment]
Closing as too old. Feel free to reopen.
