### ISSUE TITLE
is there any plan to create support beanstalkd in Windows xp to Windows 8?

### ISSUE THREAD

**Issue by ajay-patel** [beanstalkd/beanstalkd#187]
is there any plan to create support beanstalkd in Windows xp to Windows 8? it will be great thanks to have an awesome queue manager in windows.

**Comment by skys215** [comment]
There is a "windows version"
https://github.com/caidongyun/beanstalkd-win
But it requires cygwin.

**Comment by caidongyun** [comment]
we had used  "select" to surpport it  . https://github.com/caidongyun/beanstalkd-win
