### ISSUE TITLE
beanstalkd 1.9 crash

### ISSUE THREAD

**Issue by tomponline** [beanstalkd/beanstalkd#199]
Hi,

Last night we experienced our first beanstalks 1.9 crash. We have been running it for about 1 month, and doing roughly 12 million jobs a day through it.

Previously we have been running 1.4.6 for about 2 years constantly, doing hundreds of millions of jobs through it. It was rock solid.

Unfortunately we have little to go on to debug it, there is nothing in the logs, cacti isn't showing any unusual activity on the server prior to the crash.

I will try and update this issue as we get more info.

**Comment by rsmck** [comment]
Just upgraded to Beanstalk 1.9 (previously using 1.4.x without issue) on moving it to a new Centos 6 x64 installation and experiencing similar problems, again not much debug information to go on... did anyone make any progress with this? 

The error in my case is as follows, but looks like it may be related? 

```kernel: beanstalkd[24767] general protection ip:4095b7 sp:7fffdfe9ece0 error:0 in beanstalkd[400000+12000]```

**Comment by silviucpp** [comment]
@tomponline this still occurs on the last version ?

**Comment by tomponline** [comment]
@silviucpp no this issue is very old and I ran it in production for many years after that with no issues.
