### ISSUE TITLE
named jobs

### ISSUE THREAD

**Issue by kr** [beanstalkd/beanstalkd#2]
Can be used, e.g., for deduplication of work.

**Comment by dapi** [comment]
+3.14

**Comment by berkayunal** [comment]
Any news on this feature?
+1

**Comment by TofuLay** [comment]
+1  I need this feature

**Comment by ozanhazer** [comment]
+1

**Comment by tabacco** [comment]
This would be super useful as a way to reduce redundant work by queue consumers. I'd love to see it make it into a future release!

**Comment by ysmolsky** [comment]
Closing in favor of #379
