### ISSUE TITLE
Reprioritise existing jobs

### ISSUE THREAD

**Issue by mloughran** [beanstalkd/beanstalkd#20]
Given a job id, I would like to be able to reprioritize it. Currently I can only achieve this by calling peek, delete, then recreating the job.

One possibility would be to allow release to be called without first having reserved the job. Currently the interface for delete and release is inconsistent:

```
put 0 0 60 3
foo
INSERTED 1
delete 1
DELETED
put 0 0 60 3
bar
INSERTED 2
release 2 100 0
NOT_FOUND
delete 2
DELETED
```

**Comment by ysmolsky** [comment]
Closed in favor of #310
