### ISSUE TITLE
Beanstalk 1.9 high CPU usage

### ISSUE THREAD

**Issue by swehner** [beanstalkd/beanstalkd#200]
I've decided to open a new issue with the beanstalk v1.9 performance issues detected by several users.

https://groups.google.com/forum/#!searchin/beanstalk-talk/performance/beanstalk-talk/DSDOE7spoio/a8l3jO0wjG0J

I've ran a callgrind benchmark on version v1.9 and v1.8, and from what I can see that due to the changes from 1d191ba26b20f402cc8e8ee3a7f7b0de9f1ff78c, prottick is called more often from srvserve which seems to be causing a higher CPU usage.
I hope this helps to debug the problems.
![profiling_1_9vs1_8](https://f.cloud.github.com/assets/273236/893266/77da8034-fa9c-11e2-8c3f-ef66bbcf8631.png)

To run the profile I've used this test program https://github.com/swehner/bsperf similar to the one matt used when sending this issue to the mailing list.

**Comment by JensRantil** [comment]
#218 might fix this.

**Comment by silviucpp** [comment]
This was fixed . Bug need to be closed

**Comment by ysmolsky** [comment]
@silviucpp, can you point to the commit/PR that fixed it?

**Comment by silviucpp** [comment]
74f6ff76d528188a6da7c11b5d77124ef82eec2c

**Comment by ysmolsky** [comment]
PR #218 looks not finished. I wonder if this is reproducible in 1.10 or especially on master. I have commented in PR, but any help investigating this issue is welcome!

**Comment by silviucpp** [comment]
I'm using in production the version b7b4a6a14b7e8d096dc8cbc255b23be17a228cbb (last major commit in master) and I never seen this problem. for this reason I doubt that this can be replicated yet.

**Comment by ysmolsky** [comment]
I have looked into this. It does not look like an issue to me on OSX and Linux. I run 1.10 in production on different Linux kernels and there is no issue with CPU consumption there.
