### ISSUE TITLE
OUT_OF_MEMORY in response to 'put 1024 0 60 10'

### ISSUE THREAD

**Issue by pentium10** [beanstalkd/beanstalkd#204]
This error is a permanent one, the environment is kinda tricky.

Beanstlkd is installed in a VM machine running ubuntu 64, version: 1.4.6

Working with beanstalkd from the same machine works ok.

But when we use from another machine, this time it was a raspberry pi. And we connect to the beanstalk setup on the ubuntu64, 
- it connects fine, 
- the use tube command runs fine,
- error occurs on the PUT job task

OUT_OF_MEMORY in response to 'put 1024 0 60 10'

**Comment by JensRantil** [comment]
@pentium10 Sorry for late response here: I assume you don't have the exact command line arguments you started beanstalk with? Can you still reproduce this? Could you output the `stats` output here? If not, feel free to close this issue.

**Comment by silviucpp** [comment]
Very old report without any feedback. I guess can be closed
