### ISSUE TITLE
Out of date install instructions for CentOS

### ISSUE THREAD

**Issue by fly2279** [beanstalkd/beanstalkd#209]
I would like to install beanstalkd on my vps that is running CentOS. I'm getting the following error:

CT-2751-bash-4.1# su -c 'rpm -Uvh http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-3.noarch.rpm'
Retrieving http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-3.noarch.rpm
curl: (6) Couldn't resolve host 'download.fedora.redhat.com'
error: skipping http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-3.noarch.rpm - transfer failed

Is there any way to accomplish this?

**Comment by ysmolsky** [comment]
We cannot fix this since it's a problem with CentOS distribution.
