### ISSUE TITLE
delay any existing job by id

### ISSUE THREAD

**Issue by sanjaymohnani** [beanstalkd/beanstalkd#222]
Is that possible to delay any existing job? As per my research, there's no any direct facility to delay any existing job.

I think, to delay any existing job, you need to delete previous one and add new one with delay information. But, in that case I'm unable to find actual tube name from which job was fetched. That also unable to get from reserve command response.

Correct me if I'm wrong.

Thank...

**Comment by JensRantil** [comment]
Please update the title to reflect the issue better. Proposal: Delay any existing job
