### ISSUE TITLE
truncated tube name has missing trailing NUL byte

### ISSUE THREAD

**Issue by setharnold** [beanstalkd/beanstalkd#224]
The tube name truncation check looks incorrect:

```
tube
make_tube(const char *name)
{
    tube t;

    t = new(struct tube);
    if (!t) return NULL;

    t->name[MAX_TUBE_NAME_LEN - 1] = '\0';
    strncpy(t->name, name, MAX_TUBE_NAME_LEN - 1);
    if (t->name[MAX_TUBE_NAME_LEN - 1] != '\0') twarnx("truncating tube name");
```

strncpy() is copying one fewer byte than the allowed tube name length -- so the last '\0' cannot be overwritten by this code. (Which is for the best, since nothing in this function would re-set that last byte if it were overwritten by the strncpy.)

Thanks

**Comment by JensRantil** [comment]
@setharnold Feel free to submit a pull request if you have the time ;)

**Comment by kr** [comment]
The check is correct, but as you point out it needs to reset the final `'\0'` afterward. Thanks for reporting this!
