### ISSUE TITLE
Beanstalk logging unexpected 'r' values

### ISSUE THREAD

**Issue by bmhatfield** [beanstalkd/beanstalkd#226]
Hi,

I'm running beanstalkd using upstart (rather than an init script), and I noticed that the beanstalkd logs are huge.

The upstart configuration I'm using is:

```
# Capture any output that makes it to stdout to /var/log/upstart/service-name.log
console log

# Run actual command
exec start-stop-daemon --start --oknodo   --exec /usr/bin/beanstalkd -- -l 0.0.0.0 -p 11300 -u beanstalkd -z 1048576
```

And beanstalkd is logging lots of lines in the format of `r number`:

```
r 208
r 19
r 19
r 19
r 19
r 208
r 25
r 25
r 208
r 25
r 25
r 208
r 208
r 25
r 208
r 19
r 19
r 19
r 25
r 208
r 19
r 25
```

What are these log messages? How can I turn them off? I've never noticed them printing when running beanstalkd directly with stdout captured.

**Comment by silviucpp** [comment]
@bmhatfield is this an issue that you can reproduce on the last master?

**Comment by ysmolsky** [comment]
From the flags I cannot determine that beanstalkd should output anything at all. Reopen if this is still an issue.
