### ISSUE TITLE
Cheap way to determine job-tube correlation

### ISSUE THREAD

**Issue by extemporalgenome** [beanstalkd/beanstalkd#231]
The existing protocol design seems to assume that if multiple tubes are watched in a connection, then they are handled homogeneously; this isn't always the case, and in some cases, it is critical to know the tube from which a reserved job came.

The current options are to open separate connections for each set of uniquely-handled tubes (splitting the heterogeneous-behavior set into homogeneous subsets), or to send the stats-job command after each reserve response.

Ideally, there'd be a variant of the reserve command with a response containing the applicable tube. Taking note that I put no effort into the command/status names (and certainly place no emphasis on them as written below), I propose:

Request:
x-reserve <timeout>\r\n

Response:
X-RESERVED <id> <tube> <bytes>\r\n
<data>\r\n

This would have identical semantics to `reserve-with-timeout` if timeout is non-negative, and would behave identically to `reserve` if supplied a negative timeout. In the response, <tube> would be the index of the corresponding tube in the watch list (relative to the order that watches were added and the list returned by `list-tubes-watched`).

Alternatively, a `job-tube <id>` command could serve a similar purpose, at the cost of an additional round-trip, which identifies the tube given a job id.

**Comment by petri** [comment]
+1 for any kind of efficient job-routing-by-tube feature; and why not just add the tube name to job metadata returned by reserve? Not that I would mind a separate command either.

**Comment by petri** [comment]
@kr what do you think? Any chance this might get implemented at some point one way or another? For example for my use case I now have to copy tube name  into the data payload of each job that is put and then parse that from each job reserved... a bit messy, not being able to use the job data purely for application data payload.

**Comment by kr** [comment]
The general philosophy of beanstalkd is that the server should only do things client's can't do on their own. Clients can put any necessary data to handle the job in the job body. This might include the tube name. Adding another command to the server for this doesn't let clients do anything they couldn't already do, so it doesn't seem like a good fit.

**Comment by JensRantil** [comment]
I agree with @kr here.
