### ISSUE TITLE
Outdated and incomplete PPAs

### ISSUE THREAD

**Issue by pataquets** [beanstalkd/beanstalkd#233]
Ubuntu PPA linked from the home page contains an outdated version (1.5).
https://launchpad.net/~jernej/+archive/beanstalkd

Also, binaries at PPA https://launchpad.net/~beanstalkd/+archive/stable/+packages for Quantal and later are missing.

**Comment by JensRantil** [comment]
> Ubuntu PPA linked from the home page contains an outdated version (1.5).
https://launchpad.net/~jernej/+archive/beanstalkd

Looks like @izacus the one who hosts that. I was unable to create a bug on his PPA (for some reasons). Maybe he could give some input here (or publish a never version of beanstalk on his PPA).

> Also, binaries at PPA https://launchpad.net/~beanstalkd/+archive/stable/+packages for Quantal and later are missing.

Looks like they are hosting version 1.9 so not an issue anymore, right?
