### ISSUE TITLE
compile error in conn.c on Solaris

### ISSUE THREAD

**Issue by pierredehaen** [beanstalkd/beanstalkd#234]
On Solaris 11 (SPARC), using gcc-4.8.0 and gmake-4.0, when compiling with -Werror I get:
x===========
gcc -Wall -Werror -Wformat=2 -g    -c -o conn.o conn.c
conn.c: In function 'make_conn':
conn.c:37:13: error: return makes pointer from integer without a cast [-Werror]
     if (!c) return twarn("OOM"), NULL;
             ^
conn.c:42:9: error: return makes pointer from integer without a cast [-Werror]
         return twarn("OOM"), NULL;
         ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'conn.o' failed
gmake: **\* [conn.o] Error 1
x===========

Thanks

**Comment by ysmolsky** [comment]
Since I do not plan to fix this on Solaris, and it's been 5 years. I am closing this. If anyone wants to fix add Solaris, feel free to send a PR.
