### ISSUE TITLE
make check does not work on Solaris

### ISSUE THREAD

**Issue by pierredehaen** [beanstalkd/beanstalkd#235]
It looks like nm does not have the same output on Solaris and on linux. For make check to work I had to do the following change:
x===============
**\* ../beanstalkd-1.9.orig/ct/gen       Sun Apr 14 19:19:41 2013
--- ct/gen      Thu May  8 15:08:53 2014

---

**\* 12,18 ****
  tests() {
      for f in "$@"
      do nm $f
!     done | cut -d ' ' -f 3 | fixsyms | egrep ^cttest
  }

  gen() {
--- 12,18 ----
  tests() {
      for f in "$@"
      do nm $f
!     done | cut -d'|' -f8 | grep cttest
  }

  gen() {
x===============

**Comment by ysmolsky** [comment]
Since I do not plan to fix this on Solaris, and it's been 5 years. I am closing this. If anyone wants to fix add Solaris, feel free to send a PR.
