### ISSUE TITLE
type warnings in main.c on Solaris

### ISSUE THREAD

**Issue by pierredehaen** [beanstalkd/beanstalkd#236]
On Solaris 10 x86:
--%<-----------
gcc -Wall -Wformat=2 -g    -c -o main.o main.c
main.c: In function `su':
main.c:23: warning: int format, gid_t arg (arg 5)
main.c:26: warning: int format, uid_t arg (arg 5)
main.c: In function`main':
main.c:60: warning: int format, pid_t arg (arg 2)
--%<-----------

Fixed with:
--%<-----------
**\* main.c.orig Sun Apr 14 19:19:41 2013
--- main.c      Sat May 10 14:45:49 2014

---

**\* 20,29 ****
      if (!pwent) twarnx("getpwnam(\"%s\"): no such user", user), exit(33);

```
  r = setgid(pwent->pw_gid);
```

!     if (r == -1) twarn("setgid(%d \"%s\")", pwent->pw_gid, user), exit(34);

```
  r = setuid(pwent->pw_uid);
```

!     if (r == -1) twarn("setuid(%d \"%s\")", pwent->pw_uid, user), exit(34);
  }

--- 20,29 ----
      if (!pwent) twarnx("getpwnam(\"%s\"): no such user", user), exit(33);

```
  r = setgid(pwent->pw_gid);
```

!     if (r == -1) twarn("setgid(%ld \"%s\")", pwent->pw_gid, user), exit(34);

```
  r = setuid(pwent->pw_uid);
```

!     if (r == -1) twarn("setuid(%ld \"%s\")", pwent->pw_uid, user), exit(34);
  }

---

**\* 57,63 ****
      optparse(&srv, argv+1);

```
  if (verbose) {
```

!         printf("pid %d\n", getpid());
      }

```
  r = make_server_socket(srv.addr, srv.port);
```

--- 57,63 ----
      optparse(&srv, argv+1);

```
  if (verbose) {
```

!         printf("pid %ld\n", getpid());
      }

```
  r = make_server_socket(srv.addr, srv.port);
```

--%<-----------

On Solaris 11 sparc:
--%<-----------
gcc -Wall -Werror -Wformat=2 -g    -c -o main.o main.c
main.c: In function 'main':
main.c:60:9: error: format '%d' expects argument of type 'int', but argument 2 has type 'pid_t' [-Werror=format=]
         printf("pid %d\n", getpid());
         ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'main.o' failed
--%<-----------

Fixed with:
--%<-----------
**\* main.c.orig Sun Apr 14 19:19:41 2013
--- main.c      Sat May 10 14:43:25 2014

---

**\* 20,29 ****
      if (!pwent) twarnx("getpwnam(\"%s\"): no such user", user), exit(33);

```
  r = setgid(pwent->pw_gid);
```

!     if (r == -1) twarn("setgid(%d \"%s\")", pwent->pw_gid, user), exit(34);

```
  r = setuid(pwent->pw_uid);
```

!     if (r == -1) twarn("setuid(%d \"%s\")", pwent->pw_uid, user), exit(34);
  }

--- 20,29 ----
      if (!pwent) twarnx("getpwnam(\"%s\"): no such user", user), exit(33);

```
  r = setgid(pwent->pw_gid);
```

!     if (r == -1) twarn("setgid(%u \"%s\")", pwent->pw_gid, user), exit(34);

```
  r = setuid(pwent->pw_uid);
```

!     if (r == -1) twarn("setuid(%u \"%s\")", pwent->pw_uid, user), exit(34);
  }

---

**\* 57,63 ****
      optparse(&srv, argv+1);

```
  if (verbose) {
```

!         printf("pid %d\n", getpid());
      }

```
  r = make_server_socket(srv.addr, srv.port);
```

--- 57,63 ----
      optparse(&srv, argv+1);

```
  if (verbose) {
```

!         printf("pid %ld\n", getpid());
      }

```
  r = make_server_socket(srv.addr, srv.port);
```

--%<-----------

**Comment by ysmolsky** [comment]
Since I do not plan to fix this on Solaris, and it's been 5 years. I am closing this. If anyone wants to fix add Solaris, feel free to send a PR.
