### ISSUE TITLE
compile and execute errors in integ-test.c on Solaris

### ISSUE THREAD

**Issue by pierredehaen** [beanstalkd/beanstalkd#237]
On Solaris 11 sparc (gcc 4.8.0) I get at compile time:
--%<------------
gcc -Wall -Werror -Wformat=2 -g    -c -o integ-test.o integ-test.c
integ-test.c: In function 'muststart':
integ-test.c:59:5: error: missing sentinel in function call [-Werror=format=]
     execlp(a0, a0, a1, a2, a3, a4, NULL);
     ^
[... repeated several times ...]
--%<------------

It is fixed with:
--%<------------
**\* integ-test.c.orig      Sun Apr 14 19:19:41 2013
--- integ-test.c        Sat May 10 14:57:31 2014

---

**\* 56,62 ****

```
  /* now in child */
```

!     execlp(a0, a0, a1, a2, a3, a4, NULL);
  }

--- 56,62 ----

```
  /* now in child */
```

!     execlp(a0, a0, a1, a2, a3, a4, (char *) NULL);
  }

---

**\* 707,713 ****
      ckresp(fd, "INSERTED 1\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 707,713 ----
      ckresp(fd, "INSERTED 1\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 731,737 ****
      ckresp(fd, "BURIED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 731,737 ----
      ckresp(fd, "BURIED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 758,764 ****
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 758,764 ----
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 792,798 ****
      assertf(gotsize == size, "binlog.2 %d != %d", gotsize, size);

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 792,798 ----
      assertf(gotsize == size, "binlog.2 %d != %d", gotsize, size);

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 822,828 ****
      }

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 822,828 ----
      }

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 874,880 ****
      ckresp(fd, "NOT_FOUND\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 874,880 ----
      ckresp(fd, "NOT_FOUND\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 943,949 ****
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 943,949 ----
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 1014,1020 ****
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 1014,1020 ----
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 1192,1196 ****
      ckrespsub(fd, "\nkicks: 0\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }
--- 1192,1196 ----
      ckrespsub(fd, "\nkicks: 0\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }
--%<------------

At execution time on Solaris 10 x86 (not on Solaris 11 sparc!?) I get:
--%<------------
cttestbinlogv5: error (exit status 1)
no beanstalkd-1.4.6 in /usr/bin /usr/local/bin /usr/ccs/bin /usr/sbin /usr/sfw/bin
beanstalkd-1.4.6 -b /tmp/beanstalkd.test.i0a4pM -p 17862
start server pid=19587
cttestbinlogv5: integ-test.c:86 in mustdiallocal: connect: Connection refused
cttestbinlogv5: integ-test.c:86 in mustdiallocal: connect: Connection refused
--%<------------

Why 1.4.6? I fixed this (and the above problem) with:
--%<------------
**\* integ-test.c.orig   Sun Apr 14 19:19:41 2013
--- integ-test.c        Sat May 10 16:20:25 2014

---

**\* 56,62 ****

```
  /* now in child */
```

!     execlp(a0, a0, a1, a2, a3, a4, NULL);
  }

--- 56,62 ----

```
  /* now in child */
```

!     execlp(a0, a0, a1, a2, a3, a4, (char *) NULL);
  }

---

**\* 707,713 ****
      ckresp(fd, "INSERTED 1\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 707,713 ----
      ckresp(fd, "INSERTED 1\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 731,737 ****
      ckresp(fd, "BURIED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 731,737 ----
      ckresp(fd, "BURIED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 758,764 ****
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 758,764 ----
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 792,798 ****
      assertf(gotsize == size, "binlog.2 %d != %d", gotsize, size);

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 792,798 ----
      assertf(gotsize == size, "binlog.2 %d != %d", gotsize, size);

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 822,828 ****
      }

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 822,828 ----
      }

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 874,880 ****
      ckresp(fd, "NOT_FOUND\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 874,880 ----
      ckresp(fd, "NOT_FOUND\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 943,949 ****
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 943,949 ----
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 1014,1020 ****
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }

--- 1014,1020 ----
      ckresp(fd, "DELETED\r\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }

---

**\* 1023,1030 ****
  {
      char portstr[10];

!     if (system("which beanstalkd-1.4.6") != 0) {
!         puts("beanstalkd 1.4.6 not found, skipping");
          exit(0);
      }

--- 1023,1030 ----
  {
      char portstr[10];

!     if (system("which beanstalkd") != 0) {
!         puts("beanstalkd not found, skipping");
          exit(0);
      }

---

**\* 1034,1040 ****
      progname=**func**;
      port = (rand()&0xfbff) + 1024;
      sprintf(portstr, "%d", port);
!     muststart("beanstalkd-1.4.6", "-b", dir, "-p", portstr);
      fd = mustdiallocal(port);
      mustsend(fd, "use test\r\n");
      ckresp(fd, "USING test\r\n");
--- 1034,1040 ----
      progname=**func**;
      port = (rand()&0xfbff) + 1024;
      sprintf(portstr, "%d", port);
!     muststart("beanstalkd", "-b", dir, "-p", portstr);
      fd = mustdiallocal(port);
      mustsend(fd, "use test\r\n");
      ckresp(fd, "USING test\r\n");

---

**\* 1192,1196 ****
      ckrespsub(fd, "\nkicks: 0\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, NULL);
  }
--- 1192,1196 ----
      ckrespsub(fd, "\nkicks: 0\n");

```
  killsrv();
```

!     execlp("rm", "rm", "-rf", dir, (char *) NULL);
  }
--%<------------

**Comment by ysmolsky** [comment]
This file is no longer present in the repo.
