### ISSUE TITLE
add a "move" command

### ISSUE THREAD

**Issue by MartinWickman** [beanstalkd/beanstalkd#240]
From: https://groups.google.com/forum/#!searchin/beanstalk-talk/bury|sort:date/beanstalk-talk/AyZhb4e6i24/5WKPuEEvTNkJ

This would be really useful to make routing jobs between tubes safer and more efficient. I'm imagining a "move" operation for a reserved job. It would be very similar to "release", but instead of returning the job to the tube from which it was reserved, it would move the job to the end of the currently used tube. 

Documentation:

The "move" command moves a reserved job into the ready queue of the  currently used tube. It is normally used when routing jobs between tubes. It looks like this: 

`move id pri delay \r\n`
- `id` is the job id to move. 
- `pri` is a new priority to assign to the job. 
- `delay` is a new integer number of seconds to wait before putting the job in    the ready queue. The job will be in the "delayed" state during this time. 

The client expects one line of response, which may be: 
- `MOVED\r\n` to indicate success. 
- `BURIED\r\n` if the server ran out of memory trying to grow the priority    queue data structure. 
-  `NOT_FOUND\r\n`if the job does not exist or is not reserved by the client.

**Comment by ysmolsky** [comment]
Not sure how it is different from the functionality of copy. The "move" could replicated by the copy command. Anyway, we do not plan to add such features for now. Also I am going to be very conservative for adding new commands. The set of commands should cover wide area. It's better to have small amount of command that are more robust and allow a lot to be implemented.
This looks like a some very specific case that can be replicated by already defined commands in protocol.

We need to focus on short-term bug fixes. I will leave it open, though.
