### ISSUE TITLE
add a "copy" command to copy/clone the job into multiple tubes

### ISSUE THREAD

**Issue by MartinWickman** [beanstalkd/beanstalkd#241]
A "copy" command  could be used to create copies of jobs into other tubes. This helps reducing complexity when jobs needs to be processed in several steps (in parallell). It's a bit tricky to keep count of these steps when a failure occur. 

For example: Say we have a tube "incoming". Each job in the tube is processed by a consumer and then the job is atomically copied to tubes "to_database" and "send_as_mail" or something. Then it would be a breeze to create consumers for each of them rather than trying to manage failures using a single tube.

The copy command should be able to copy the job to several tubes at once.

To reduce memory usage, an optimization would be not to perform a memcpy of the job struct, but rather copy references (pointers) to the target tubes instead. I'm not sure if that is possible though.

**Comment by ysmolsky** [comment]
I have set the wrong label, since this feature is not decided upon (yet).
