### ISSUE TITLE
Not handling signals

### ISSUE THREAD

**Issue by kuon** [beanstalkd/beanstalkd#243]
It seems that SIGTERM is not handled per this commit:

https://github.com/kr/beanstalkd/commit/8c0633c7759d8c35b4c383b471ab6efcfa9fbfc0#diff-2045016cb90d1e65d71c2407a2570927L82

Is this intended? It is not practical to have to kill -9 the process.

**Comment by hozn** [comment]
Is there any update on this ? -- It does not appear to be fixed in v1.10, providing a bit of a frustrating experience when running in Docker.

**Comment by ysmolsky** [comment]
I have noticed myself the same behavior in Docker too, but I never dig into that. When I run server locally SIGTERM works as expected. Docker is supposed to propagate SIGTERM to the first process that is being run.

**Comment by ysmolsky** [comment]
This will be fixed in PR #528 and see issue #527 for the details.
