### ISSUE TITLE
Feature request: event watchers

### ISSUE THREAD

**Issue by bra-fsn** [beanstalkd/beanstalkd#244]
It would be nice to have event watchers. Delete comes to my mind (for my use case) first.

Python sample here:

``` python
client_C>>> beanstalk.watch(operation='delete') # multiple watchers can be configured
client_C>>> job = beanstalk.reserve()
client_A>>> beanstalk.put('job')
client_B>>> beanstalk.reserve().delete()
client_C>>> job.stats()
{
... all normal fields for the task, so the watcher can see what was it...
'operation': 'delete'
}
```

**Comment by JensRantil** [comment]
A workaround: Simply have you deleting client add a job to your "deleted jobs" tube. Your watcher then simply reserves job from that "deleted jobs" tube. @kr @bra-fsn You think that workaround would be enough? I do.

**Comment by kr** [comment]
Yes. Note that that sort of thing would be easier to manage with #3.

**Comment by ysmolsky** [comment]
closing in favor of #3
