### ISSUE TITLE
binlog compaction not always working?

### ISSUE THREAD

**Issue by jaydiablo** [beanstalkd/beanstalkd#246]
We're running beanstalkd 1.9-2.el6 in production, and run multiple millions of jobs through it on a monthly basis.  We make heavy use of the delay queue.

We were running beanstalkd before 1.5 came out, so have ran into the binlog growing out of control issue (#43), but after 1.5 that seemed to have been fixed, until recently.  I can't pinpoint a specific release, or if it's even because of a change to beanstalkd (perhaps our volume + our use of the delay queue are the issue?), but twice this year we've had to deal with the binlog growing out of control.  Yesterday it was a 30 gig file, which beanstalkd took forever to process on a startup (we don't have to restart beanstalkd very often, thankfully).  We ended up starting a new server, and migrating the jobs to it (custom script does this process).  Once the jobs were migrated over, the new binlog on the new machine was only 1.6 gigs.  In the migration process we intentionally left some buried jobs behind, which kept the old server's binlog at 15 gigs (~1,500 binlog files, ~400 buried jobs).  We haven't tried it yet, but I assume that deleting those buried jobs will cause the log to prune down to nearly 0 bytes, which is behavior we've seen in the past, particularly pre-1.5.

I double checked that we aren't running beanstalkd with the "-n" flag, so compaction should be on. Here's the command line flags that are being passed to beanstalkd during startup:

`/usr/bin/beanstalkd -l 0.0.0.0 -p 11300 -b /var/lib/beanstalkd/binlog -f 100 -s 10485760`

I believe these are mostly the default values for beanstalkd.

Any insight as to why the binlogs aren't being cleaned up as jobs are removed?  The issue seems identical to that described in #43.

We'll retain the 15 gig log file for the time being in case there is anything you'd like me to test against it.

**Comment by rfeiner** [comment]
We hit the same issue. We had 5mio delayed jobs in one tube. Delay times are various up to 5 days. We now had around 66GB of binlogs that were not being cleaned. 

We 'fixed' it by deleting all the delayed jobs using peek-delayed + delete the jobs. The binlogs are being deleted during and after the process (it's not being done instantly).

Is compaction working for binlogs with delayed jobs too? Or only for buried jobs?

**Comment by ysmolsky** [comment]
Guys, are you still experience this issue with v1.10? If yes, can you try recently released version v1.11? Please let me know if I should reopen this issue since it seems to be an old one.

**Comment by hkmaly** [comment]
Just a note: I upgraded some old beanstalkd to version 1.10 and then noticed that I have this problem. Specifically, I had some very old jobs in "ready" state in some testing tubes (not really touched for long time) and some also very old jobs delayed and re-failed-to-process-ed every five seconds, and there was no compaction, those few kilobytes kept few gigabites of logs around.

However, considering I don't need the testing tubes, those delayed ones needed to be fixed anyway, and the possibility it only happened because while 1.10 was running, the jobs were created in version older than 1.10, I'm not testing v1.11 ... I will complain if the issue appears again.

**Comment by ysmolsky** [comment]
Please let me know if you encounter these again. If you could send the dump of binlogs somehow that would be great. Or at least print the those jobs infos. Any info to reproduce the bug is much appreciated!

**Comment by ysmolsky** [comment]
One note. I have closed this ticket because it is old and does not contain anything actionable. I mean nothing to reproduce and no way to fix this.

**Comment by jaydiablo** [comment]
We've just deployed a `1.11` instance and will be monitoring the disk usage over time, it may take some time to see the negative effects, but will report back.
