### ISSUE TITLE
Issue with peek-ready and delete command

### ISSUE THREAD

**Issue by arjunsharma1** [beanstalkd/beanstalkd#258]
![bug](https://cloud.githubusercontent.com/assets/7428073/5280125/f932156e-7b12-11e4-8453-d985da69ea94.png)

Sometime peek-ready command not give correct job.
Sometime delete command not delete job.

**Comment by silviucpp** [comment]
@arjunsharma1 can you please provide more steps or maybe a sample code to replicate this issue ?

**Comment by arjunsharma1** [comment]
This issue is generated by command line.

Steps :-

1) Put messages in beanstalkd using STOMP by php client in regular interval.
2) Then use peek-ready command to consume messages(for example it is showing taskId 312191)
3) Use delete command to acknowledge then some time it was not delete the task.

**Comment by JensRantil** [comment]
@arjunsharma1 Which version of beanstalkd? Could you provide sample code? What is STOMP?

Looking at your screenshot, was there any other client connected to beanstalkd when you were doing that the test?

PS. Next could be nice if you copied the actual terminal output, not screenshot.

**Comment by arjunsharma1** [comment]
STOMP is simple text oriented messaging protocol.

There is no client connected.

Currently we are using other solution instead of beanstalkd.

**Comment by ysmolsky** [comment]
The example in the topic is not reproducible. It seems that there is another client connected to the tube in author's case.
I tried to reproduce but I fail to see an error:
```
% nc 127.0.0.1 11000 -c
use qwe
USING qwe
put 123
BAD_FORMAT
put 0 0 60 3
123
INSERTED 1
peek-ready
FOUND 1 3
123
peek-ready
FOUND 1 3
123
peek-ready
FOUND 1 3
123
put 0 0 60 3
qwe
INSERTED 2
peek-ready
FOUND 1 3
123
delete 1
DELETED
peek-ready
FOUND 2 3
qwe
```

Closing.
