### ISSUE TITLE
How to enable logging(syslog, or cusom file)?

### ISSUE THREAD

**Issue by jsmirnov** [beanstalkd/beanstalkd#260]
https://stackoverflow.com/questions/27850384/beanstalkd-doesnt-write-logs

I am unable to configure logging for beanstalkd. 

As far as I see in init.d script following lines of code, I assume there should be some form of logging, but how to enable it?

```
...

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

...

DAEMON=/usr/bin/beanstalkd # Introduce the server's location here
NAME=beanstalkd             # Introduce the short server's name here
DESC="in-memory queueing server" # Introduce a short description here
#LOGDIR=/var/log/beanstalkd  # Log directory to use

...


#LOGFILE=$LOGDIR/$NAME.log  # Server logfile
DAEMONUSER=beanstalkd   # Users to run the daemons as. If this value
                        # is set start-stop-daemon will chuid the server
```

**Comment by pentium10** [comment]
The request for log are also mentioned in #229

**Comment by ifduyue** [comment]
There's a `-V` option, which will increase verbosity.

**Comment by jonathanpmartins** [comment]
A log file is much more easy! :(

**Comment by geerlingguy** [comment]
And just noting it's a `-V` (capital) and not `-v` (lower)—the latter will just print version info.

**Comment by ysmolsky** [comment]
https://github.com/beanstalkd/beanstalkd/issues/229#issuecomment-114750350

> There is a flag -v that causes beanstalkd to be more verbose on stdout. You can give it multiple times to increase the verbosity. If you want to save the log, you can redirect stdout to a file or pipe it to a log rotation utility.
