### ISSUE TITLE
reserved job is not released

### ISSUE THREAD

**Issue by agamjain2012** [beanstalkd/beanstalkd#262]
i had the job id. here is the output from job.stats() 
{'buries': 0, 'time-left': -4220, 'releases': 0, 'tube': 'jobs', 'timeouts': 0, 'ttr': 120, 'age': 4379, 'pri': 1024, 'delay': 0, 'state': 'reserved', 'reserves': 1, 'file': 0, 'kicks': 0, 'id': 1942968}

**Comment by cincodenada** [comment]
Not the author, but what were you doing when the job ended up in this state?  Can you make it happen again, and if so, what are the steps to reproduce?

**Comment by SyBernot** [comment]
I've had this happen once or twice in the last 2 years. Mine was a corrupted binlog. I had to drain the queues stop the service and and delete the binlog to get it to go away, otherwise it wasn't really hurting anything that I could tell.

**Comment by agamjain2012** [comment]
we are hosted on ec2, the architecture is that these jobs are reserved by spot instances (java processes on them) and are deleted when finished.
what i have noticed is spots termination has a correlation with creating such situations. these jobs are not returned to the ready queue for a long time(in hours) and when they are they are like any other normal job in the ready queue
to filter them out we've build an application level check based on their payload.
what i suspect is that there is some sort of discrepancy in the way we poll each connection (epoll_wait, i think). I’ve tried to reproduce it on local network with no success

**Comment by sanjeethr** [comment]
I have the exact same scenario in one of our production servers. I got a core dump and this is what I observed
stats-job 68722459
OK 175
---
id: 68722459
tube: googlix-prod
state: reserved
pri: 10
age: 306064
delay: 0
ttr: 300
time-left: -303468
file: 3706
reserves: 1
timeouts: 0
releases: 0
buries: 0
kicks: 0

(gdb) p 68722459 % 98387
$102 = 48333
(gdb) p all_jobs[$102]
$103 = (job) 0x39016c0
(gdb) p *$103
$104 = {
  r = {
    id = 68722459, 
    pri = 10, 
    delay = 0, 
    ttr = 300000000000, 
    body_size = 223, 
    created_at = 1473824652021050000, 
    deadline_at = 1473827248488006000, 
    reserve_ct = 1, 
    timeout_ct = 0, 
    release_ct = 0, 
    bury_ct = 0, 
    kick_ct = 0, 
    state = 2 '\002'
  }, 
  pad = "\000\000\000\000\000", 
  tube = 0x65ae10, 
  prev = 0x45718f0, 
  next = 0x39d42b0, 
  ht_next = 0x0, 
  heap_index = 18446744073709551615, 
  file = 0x3b6eb20, 
  fnext = 0x394fec0, 
  fprev = 0x3b6eb50, 
  reserver = 0x4571680, 
  walresv = -9167, 
  walused = 319, 
  body = 0x39016c0 "\033\237\030\004"
}

Then I looked at the reserver which is the connection on which this job is reserved
(gdb) p  *(Conn *)0x4571680
$79 = {
  srv = 0x611700, 
  sock = {
    fd = 7, 
    f = 0x409ece <prothandle>, 
    x = 0x4571680, 
    added = 1
  }, 
  state = 0 '\000', 
  type = 2 '\002', 
  next = 0x0, 
  use = 0x65ae10, 
  tickat = 1473827248488006000, 
  tickpos = -1, 
  soonest_job = 0x39016c0, 
  rw = 114, 
  pending_timeout = -1, 
  halfclosed = 0 '\000', 
  cmd = "release 68735830 1024 60\000\n", '\000' <repeats 181 times>, 
  cmd_len = 0, 
  cmd_read = 0, 
  reply = 0x40e2f7 "RELEASED\r\n", 
  reply_len = 10, 
  reply_sent = 0, 
  reply_buf = "OK 168\r\n\000\066\070\067\063\065\070\064\063 215\r\n", '\000' <repeats 184 times>, 
  in_job_read = 0, 
  in_job = 0x0, 
  out_job = 0x0, 
  out_job_sent = 170, 
  watch = {
    used = 1, 
    cap = 2, 
    last = 0, 
    items = 0x7bbe80, 
    oninsert = 0x401c28 <on_watch>, 
    onremove = 0x401c61 <on_ignore>
  }, 
  reserved_jobs = {

    r = {
      id = 0, 
      pri = 0, 
      delay = 0, 
      ttr = 0, 
      body_size = 0, 
      created_at = 0, 
      deadline_at = 0, 
      reserve_ct = 0, 
      timeout_ct = 0, 
      release_ct = 0, 
      bury_ct = 0, 
      kick_ct = 0, 
      state = 0 '\000'
    }, 
    pad = "\000\000\000\000\000", 
    tube = 0x0, 
    prev = 0xe552e0, 
---Type <return> to continue, or q <return> to quit---
    next = 0x39016c0, 
    ht_next = 0x0, 
    heap_index = 0, 
    file = 0x0, 
    fnext = 0x0, 
    fprev = 0x0, 
    reserver = 0x0, 
    walresv = 0, 
    walused = 0, 
    body = 0x4571680 ""
  }
}

In this if you look at soonestjob this is the same as the job that is not released back. I'm trying to wade through the code to figure what could have gone wrong. For some reason the function conn_timeout is not triggered for this Connection. When I dumped the server data.this connection was not present in the list of Connections. 
(gdb) p srv
$105 = {
  port = 0x7ffd207f0f54 "11300", 
  addr = 0x0, 
  user = 0x0, 
  wal = {
    filesize = 10485760, 
    use = 1, 
    dir = 0x7ffd207f0f3d "/var/lib/beanstalkd", 
    head = 0x3b6ed70, 
    cur = 0x3b6eb20, 
    tail = 0x3b6eb20, 
    nfile = 2, 
    next = 3677, 
    resv = 3276, 
    alive = 18790, 
    nmig = 89146, 
    nrec = 91146389, 
    wantsync = 0, 
    syncrate = 0, 
    lastsync = 0, 
    nocomp = 0
  }, 
  sock = {
    fd = 3, 
    f = 0x40b496 <srvaccept>, 
    x = 0x611700, 
    added = 1
  }, 
  conns = {
    cap = 14, 
    len = 3, 
    data = 0x65a4c0, 
    less = 0x402193 <connless>, 
    rec = 0x4021ba <connrec>
  }
}
(gdb) p (Conn *)srv->conns->data[0]
$106 = (Conn *) 0x109cfb0
(gdb) p (Conn *)srv->conns->data[1]
$107 = (Conn *) 0x3134a20
(gdb) p (Conn *)srv->conns->data[2]
$108 = (Conn *) 0x32f2150


Note that the conns->len is only 3 and 0x4571680 is not there.
Is there anything else I need to be looking at?Any pointers? Also let me know if any other information would help debug this better

(If i restart the client these jobs do get released.)

**Comment by ysmolsky** [comment]
Without a core dump it's next to impossible to fix this kind of error. If anyone can share core dump (that will contain everything that is inside of beanstalkd), I would be glad to look at and try to fix this. 
[How to get a core dump for a segfault on Linux](https://jvns.ca/blog/2018/04/28/debugging-a-segfault-on-linux/)
