### ISSUE TITLE
compilation fails with musl

### ISSUE THREAD

**Issue by bougyman** [beanstalkd/beanstalkd#263]
Build output available at http://build.voidlinux.eu/builders/x86_64-musl_builder/builds/185/steps/shell_3/logs/stdio. This is on voidlinux. It seems musl warns if that sys/ prefix is used. Can be worked around by not using -Wall, but I'd rather not change that option. Will see if I can come up with a PR, but my c is crusty.

**Comment by bougyman** [comment]
```
sed -i 's,sys/fcntl.h,fcntl.h,' sd-daemon.c
```

Takes care of it. Figured that's to little to warrent a PR.

**Comment by jabdoa2** [comment]
A PR would be just fine for that. Please create it!

**Comment by pprindeville** [comment]
> A PR would be just fine for that. Please create it!

See PR #342.

**Comment by JensRantil** [comment]
@bougyman Still an issue now that #342 is merged? I'll close this. Let me know if still an issue.
