### ISSUE TITLE
persistent jobs

### ISSUE THREAD

**Issue by mojbenzcar** [beanstalkd/beanstalkd#269]
How to make jobs persistent .FAQ suggested putting -b option but how to run beanstalkd with that can anyone help??

**Comment by slayercat** [comment]
do you mean auto re-run job on particular time? I don't think it's good to use beanstack for that purpose.

**Comment by Perlover** [comment]
I think did you mean jobs from failover? The beanstalkd has a -b option, yes, but all jobs will be flushed to disk. I think it's not good for performance. The beanstalk keeps all jobs in memory by default. There is only one way to keep them before shutdown - to write tools for reading/writting to disk before shutdown and loading after starting again. Or to use -b option but it's not fine solution for performace as i think (i didn't use this option)

**Comment by JensRantil** [comment]
Typo in issue title.

**Comment by JensRantil** [comment]
I'm going to close this. Please let me know if still an issues.
