### ISSUE TITLE
Is there a way to migrate all jobs to another server safely?

### ISSUE THREAD

**Issue by psjay** [beanstalkd/beanstalkd#270]

**Comment by kr** [comment]
It depends on what exactly you mean by "safely".

A client can reserve all jobs from server A and insert them into server B. However, depending on whether it deletes the original job before inserting the copy, failures can result in duplicate copies of a job or a job being lost. This might be ok; it depends on the application. These types of failure are fundamental to distributed systems, and can't be overcome without an algorithm like Paxos or Raft, which beanstalkd doesn't do.

If the servers have the same architecture and are using the same C compiler, you can shut down the server A, move its binlog to server B, and start the process there. This incurs downtime.

**Comment by sbrawner** [comment]
Also there is a github project called beanstalk-tools that has a ruby exporter script... if you have the time.

In any case you will have to drain the server A beanstalk before anything else.

**Comment by JensRantil** [comment]
Since the question doesn't state doing the migration online or offline; If you are running beanstalkd using write-ahead log you could simply shut down the server and transfer it to a different server.

Disclaimer: I've never tried that, but assume it should work.

**Comment by nathanielks** [comment]
Question: I've cloned the server where beanstalkd is running with persistance, however once beanstalkd appears to have loaded the events into memory, the process crashes with no information written to /var/log/syslog. Is there a way to debug what's going on? It's running 1.10

**Comment by JensRantil** [comment]
@nathanielks I suggest you open up a separate issue about this.

@kr I suggest this can be closed as no further reply has been coming in.

**Comment by raulp** [comment]
i did migrate my jobs from one server to another in both ways described here and it worked just fine.
1) if you can't shut off, simply have a script that reads jobs from A to B. Once B acknowledged the insert, delete from A.
2) shut down A, copy the binlog folder ( /var/lib/beanstalked/binlog ), start B. Worked like a charm.

I want to test one day multi servers reading and sharing the binlogs via NFS ;) Did anyone tried that ?

**Comment by JensRantil** [comment]
> I want to test one day multi servers reading and sharing the binlogs via NFS ;) Did anyone tried that ?

@raulp You can't have multiple beanstalkd instances using the same binlog at the same time, if that's what you meant.

**Comment by raulp** [comment]
Thanks @JensRantil 
what i can do is a keepalived script to failover the instance if 1 server dies. So, not having them running at the same time, just start if server A dies. But good to know i can't have both listening on the same binlogs.

**Comment by JensRantil** [comment]
Ah, I see :+1: Cool. I guess that would, but _really_ don't want to beanstalk instances using the same binlog. Could happen all sorts of nasty stuff. Configure you keepalived correctly ;)

**Comment by xgt001** [comment]
Sorry for bumping the old thread here:

I have a heap of binlog files from a particular date. Will it be fine if I delete these binlog files? I have already extracted the all the buried job information through beanstool and saved them into seperate files.

**Comment by JensRantil** [comment]
@xgt001 If you feel comfortable that you've extracted all jobs, you should be able remove the files.

@kr @psjay I propose this issue can be closed and all questions have been adressed.
