### ISSUE TITLE
 Exception Beaneater   ExpectedCrlfError 

### ISSUE THREAD

**Issue by gandhi380** [beanstalkd/beanstalkd#277]
Hi all,

We have a server in production that's started to throw out the error "ExpectedCrlfError" over and over.   I'm not sure what's causing this issue because we have two other servers with the same configuration that don't have this issue.   We've tried restarting service, rebooting the box, and have had no luick>   Any advice you could offer would be great. 

Thanks
CG

**Comment by JensRantil** [comment]
@gandhi380 Just making sure, could it be that your client isn't using CRLF line ending while the other clients are?

**Comment by gandhi380** [comment]
i'm pretty sure its not that because the other machines have the same code and don't have this problem

**Comment by JensRantil** [comment]
@gandhi380 ...and your other machines also have the same locale?

**Comment by gandhi380** [comment]
yes

**Comment by JensRantil** [comment]
@gandhi380 An idea would be to tcpdump some of the trafic to make sure it looks valid.

**Comment by JensRantil** [comment]
I'm going to close this. Pretty sure this is an issue with https://github.com/beanstalkd/beaneater and not the server. Please file an issue there if the problem still persists.
