### ISSUE TITLE
job stuck, no way to release/delete/bury

### ISSUE THREAD

**Issue by theluk** [beanstalkd/beanstalkd#282]
Hi,

I get recently many errors while trying to reserve a Job. I´m using David Perssons (https://github.com/davidpersson/beanstalk) php implementation and want to figure out, how to fix this issue. 

while reserving 

```
reserve-with-timeout 60\r\n
```

I get a result where none of the following is present: RESERVED, DEADLINE_SOON, TIMED_OUT
instead i get something like this

```
ttps://myhost/somelink";s:2:"ip";s:14:"211.xxx.181.xx";s:8:"location";s:20:"Seoul-t'ukpyolsi
```

The thing is, i cannot get the ID, i cannot delete or release or bury this Job. 

is this a beanstalk or an sdk issue?

**Comment by JensRantil** [comment]
@theluk Could you telnet into your beanstalkd instance and enter `reserve-with-timeout 60`? That should make it possible for you to test if the issue is in PHP library or in beanstalkd?

**Comment by silviucpp** [comment]
@theluk you can you try also using this library : https://github.com/pda/pheanstalk
Seems the most active and mature php library available (my personal opinion)

Silviu

**Comment by ysmolsky** [comment]
It looks like an issue with the client. 
@theluk, were you able to figure out this problem?
I will leave this open for a while.

**Comment by ysmolsky** [comment]
I’m closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
