### ISSUE TITLE
protocol doc is hard to find on website

### ISSUE THREAD

**Issue by JensRantil** [beanstalkd/beanstalkd#304]
**Background:** The protocol document is a rather important document that not only defines the protocol, but it's also the most comprehensive document when it comes to describing exactly the features that beanstalkd has. When I'm am about to read the [protocol doc](), this is generally what I do:
1. Go to http://kr.github.io/beanstalkd/.
2. Click [FAQ](https://github.com/kr/beanstalkd/wiki/faq) in the menu.
3. Scroll down to https://github.com/kr/beanstalkd/wiki/faq#what-if-i-want-to-poll-is-there-a-reserve-command-with-a-timeout.
4. Click the "[Protocol doc](https://raw.github.com/kr/beanstalkd/master/doc/protocol.txt)" link.

An alternative approach is for a visitor to find herself to this Github repository, click "doc" directory and "protocol.txt".

Is there an access path that I've missed?

**Issue:** 3-4 clicks to find the most important document in this project.

**Proposal:**
- Either adding a link to the document in the main menu of the website; or
- Adding a link on the frontpage.

Any other approaches? Input on this?

**Comment by raulp** [comment]
Or just add it in the FAQ page as a menu and make it a direct link to the protocol.txt ;)

**Comment by ysmolsky** [comment]
This is a still valid issue. I found myself often doing too many click to find the protocol.
I will fix README.md.

@tomponline what do you think about adding link to the website here?
<img width="764" alt="Screen Shot 2019-06-30 at 10 42 32" src="https://user-images.githubusercontent.com/140245/60393808-ddde3a00-9b23-11e9-8bf7-2c6c5cfbd601.png">

**Comment by tomponline** [comment]
@ysmolsky yes that would be OK, even better would be in top menu, the FAQ bit seems too wide and on some browsers the client libs item is not displayed fully, so it could do with a refresh.

**Comment by ysmolsky** [comment]
> @ysmolsky yes that would be OK, even better would be in top menu, the FAQ bit seems too wide and on some browsers the client libs item is not displayed fully, so it could do with a refresh.

Top menu sounds even better.

**Comment by ysmolsky** [comment]
@tomponline would you be able to handle this any time soon?

**Comment by tomponline** [comment]
@ysmolsky yes I will look at it soon, hopefully tomorrow (newborn son is taking up quite a lot of my free time these days though :))
