### ISSUE TITLE
Comment question

### ISSUE THREAD

**Issue by JensRantil** [beanstalkd/beanstalkd#311]
I just spend some time reading some code. The documentation for `read_delay` states

``` c
/* Read a delay value from the given buffer and place it in delay.
 * The interface and behavior are analogous to read_pri(). */
```

. However, its implementation is quite different from `read_pri`. Is the comment really valid?

**Comment by ysmolsky** [comment]
read_delay is just a wrapper doing additional check and convertation. But documentation is a bit off in many places including this. Especially confusing is the fact that there are way to many different kinds of ints here and there. Closing this ticket.
