### ISSUE TITLE
proposal: off-load job bodies to WAL

### ISSUE THREAD

**Issue by JensRantil** [beanstalkd/beanstalkd#321]
**Issue:** Jobs with larger bodies takes up a lot of memory space if queued up.

**Idea:** When write-ahead-log (WAL) is enabled, the job body is already persisted to disk. How about allowing using the WAL as job body storage (enabled using a parameter on startup). The in-memory job body would essentially only have store refer to `(walfile, offset, size)`. A rewrite of a WAL need update the in-memory jobs.

Clearly needs investigation, but theory here is that the OS disk cache generally will make sure to cache the pages in its disk cache, so performance will not be as bad as it sounds.

API will remain unchanged.

**Counter-arguments that I can come up with:**
- Complexity in code base. I guess we'll have a to weigh this against the usefulness of the feature.
- There is a workaround. See below.

**Workaround:** Manually storing the job body on disk somewhere. Introduces complexity to make sure file blobs are removed/added correctly etc. Also, creating many files is both bad in terms of performance (for spinning disks), but also in terms of resource usage (inodes/disk usage).

Anyone's interested in this? What do you think?

**Comment by Roguelazer** [comment]
This would be great!

**Comment by ysmolsky** [comment]
This is too complex to implement in the code. File handling code is not ideal, and implementing this feature would make it even more harder. Memory is cheap, and I do not think that converting beanstalkd into some kind of database is a good thing.
