### ISSUE TITLE
Help support Travis CI containerized mode

### ISSUE THREAD

**Issue by petri** [beanstalkd/beanstalkd#322]
There are benefits to switching to Travis CI containerized mode. However currently software using beanstalkd package cannot be be run in Travis containerized mode.

Background on Travis containerized mode:
- https://docs.travis-ci.com/user/workers/container-based-infrastructure/
- https://docs.travis-ci.com/user/migrating-from-legacy/

I have already [opened a ticket on Travis to enable beanstalkd](https://github.com/travis-ci/apt-package-whitelist/issues/780). Please see [the issue comments](https://github.com/travis-ci/apt-package-whitelist/issues/780) for details, but it seems that apparently beanstalk packaged install always / by default changes user on startup, which Travis containerized mode does not allow.

Can this be changed in beanstalkd? Or if not outright changed, can a new install/startup option be added so that beanstalk would comply with the Travis containerized mode? Or should an issue be filed on platform (Debian) package instead?

Or, would there be a way to work around the Travis CI limitation?

**Comment by sergeyklay** [comment]
Try [Using Docker in Builds](https://docs.travis-ci.com/user/docker/) :)

**Comment by kr** [comment]
I'm not sure exactly what you're asking for here. Beanstalkd has a flag `-u` to switch the user on startup. If you don't supply that option, it won't switch user. Does that address your problem?

**Comment by JensRantil** [comment]
Closing this. Let me know if still an issue.
