### ISSUE TITLE
Add support for put-in-tube command

### ISSUE THREAD

**Issue by silviucpp** [beanstalkd/beanstalkd#332]
Many clients like Pheanstalk, ebeanstalkd offers this functionality by sending 2 commands : use and put .

From my tests this is decreasing the performances a lot.
Using this new command the job is sent in the desired tube using one single request and has the same performances as put command.

Command format is :

   put-in-tube tube pri delay ttr length\r\n
   data\r\n

I sent also a pull request: https://github.com/kr/beanstalkd/pull/331

Waiting for feedback,

Silviu

**Comment by JensRantil** [comment]
I think this sounds like a sane usecase.

**Comment by silviucpp** [comment]
Yes because usually you have a pool of connections and probably a set of tubes where you send jobs. Switching between tubes all day long will decrease the performances

Silviu

**Comment by kr** [comment]
The usual minimum bar for adding commands to the server is if it allows clients to do something they otherwise couldn't. This performance optimization is already available to clients if they do pipelining, so I don't see a compelling reason to add it to the server.

**Comment by silviucpp** [comment]
Hello @kr I tested with pipelining  as well before taking the decision to implement this command. 

The test was performed with client and server on different machines. As client I used https://github.com/silviucpp/ebeanstalkd (I wrote this client and it's using pipelineing and also the new command)

Here are my results with a pool of 10 connections:

put: 72411 ops/s
put-in-tube (send use followed by put): 37425 ops/s
put-in-tube (the new command): 72321 ops/s

As you can see from my tests results shows a massive downgrade in performances when you use use and put to achieve this.

Let me know if I'm doing something wrong in my tests or you have other results in your benchmarks

Silviu

**Comment by kr** [comment]
Is this the put-in-tube (send use followed by put) implementation you're referring to?

```erlang
put_in_tube(InstanceRef, Tube, Data, Params) ->
    case use(InstanceRef, Tube) of
        {using, _} ->
            put(InstanceRef, Data, Params);
        UnexpectedError ->
            UnexpectedError
    end.
```

By my reading, this looks like it inspects the result of the use command before sending the put command. That would mean it's not pipelining this command sequence.

**Comment by silviucpp** [comment]
@kr,

Yes that's the command and yes there is no pipeline between use and put otherwise how can you treat potential errors ?

Silviu

**Comment by JensRantil** [comment]
@silviucpp You don't need to look at the response immediately. You can send multiple requests and then have a look at them returned errors later in a larger batch. This works since TCP in/out streams essentially are independent.

If you are a Go programmer, https://golang.org/pkg/net/textproto/#Pipeline has a nice abstraction that might be a nice inspiration when writing a pipelining client.

> I think this sounds like a sane usecase.

I rest my case. Pipelining will do :)

**Comment by silviucpp** [comment]
@JensRantil  in case the use fails and put succeed you can break your app by putting wrong data in wrong tubes. I personally see this as being transnational.

**Comment by JensRantil** [comment]
Yes, I guess that's the tradeoff. That said, if that happens you have a bug in your beanstalkd client which probably is a bigger issue. Also, if speed really is an issue for you probably also want to pipeline your `put` requests.

What do you mean by transnational?

**Comment by silviucpp** [comment]
Sorry I was referring to transactional. I mean I personally see here the use/put being part of a single transaction. If one fails both should failed. Also the use command can fail if there is no available memory to create a new tube in case doesn't exist. 

Also I don't see how in languages like php you can implement fully pipelining :) anyway.

**Comment by spacewander** [comment]
In our project, we use a connection pool to solve the problem.
To use a tube, we will first try to get a connection which has sent `use TUBE` to beanstalkd. Once we can't get one, a new connection will be created and use the specific tube. Then the new created connection will be put into connection pool with key `HOST:PORT:use:TUBE` to reuse.

**Comment by silviucpp** [comment]
We are using connection pool as well. but instead having a pool for each tube we have a pool for all tubes and use this new command that doesn't bring any overhead.
