### ISSUE TITLE
Tag Release for Recent Commits

### ISSUE THREAD

**Issue by Mochnant** [beanstalkd/beanstalkd#335]
There were a number of commits in April that would be useful to have in a release.  Would it be possible to tag them as 1.11 and release?

**Comment by ifduyue** [comment]
+1

Shrink sparse hashmap is an important feature.

**Comment by tomponline** [comment]
Is there any news on this? Having a new tagged version of master would be great.

**Comment by Mochnant** [comment]
Does anyone other than @kr have the ability to do it?

**Comment by kamrava** [comment]
+1 ping @kr

**Comment by matteocontrini** [comment]
Up @kr

**Comment by pmarkoulidakis** [comment]
ping @kr

**Comment by empqruy** [comment]
ping @kr

**Comment by ysmolsky** [comment]
Closing in favor of #399
