### ISSUE TITLE
Makefile: make it cross-compilation friendly

### ISSUE THREAD

**Issue by pprindeville** [beanstalkd/beanstalkd#339]
I'm porting this package to OpenWRT.

I've noticed a few things...  (1) `rawfalloc()` should call `ftruncate()` instead as this is more portable than `posix_fallocate()`, and (2) it's not uncommon (in a cross-compile) for `PREFIX`, `BINDIR`, `CFLAGS`, `LDFLAGS`, `GCC`, and `LD`, to be externally seeded...

So, rather than setting `CFLAGS` as:

```
CFLAGS=-Wall -Werror\
       -Wformat=2\
       -g\

```

I'd supplement `CFLAGS` as:

```
CFLAGS += -Wall -Werror -Wformat=2 -g
```

and ditto for `LDFLAGS`, etc.  Assume that `PREFIX` might also be set, i.e.:

```
PREFIX ?= /usr/local
```

ditto for `INSTALL`, `BINDIR`, etc.

See PR #340.

**Comment by pprindeville** [comment]
What's the schedule for the next release, btw?

**Comment by sergeyklay** [comment]
@pprindeville https://github.com/kr/beanstalkd/issues/299

**Comment by pprindeville** [comment]
@sergeyklay: So...  I should be using https://github.com/silviucpp/beanstalkd-deb instead?

**Comment by sergeyklay** [comment]
I have no idea :)

**Comment by silviucpp** [comment]
Hello guys,

The mention project is only a way to create yourself a DEB that can be installed on ubuntu using the last beanstalkd master.  In case you want another revision or fork you only need to change the properties in 
https://github.com/silviucpp/beanstalkd-deb/blob/master/setup/setup.properties

This anyway doesn't solve the problem that beanstalkd is not longer an active maintain project.

Silviu

**Comment by ysmolsky** [comment]
@pprindeville I totally support this initiative. Would you be so kind to update your PR because we have changed Makefile recently?

**Comment by pprindeville** [comment]
> I totally support this initiative. Would you be so kind to update your PR because we have changed Makefile recently?

@ysmolsky Done.
