### ISSUE TITLE
segfault under cygwin on Windows

### ISSUE THREAD

**Issue by lizhangyong** [beanstalkd/beanstalkd#343]
Hi all, 

We have experienced a segmentfault when using beanstalkd windows version. It occured almost on every servers in production even though light load.

Here is more information.

1. The beanstalkd.exe is compiled by CygWin (GNU bash Version 4.3.42(4)-release (i686-pc-cygwin))

2. The beanstalk version used: beanstalkd 1.10 --https://github.com/caidongyun/beanstalkd
   The command is:  beanstalkd.exe -l 127.0.0.1 -p 11300 -z 1048575  -b "bst\binlog" -f 1000 

3. There is a stackdump files generated, the content is:
```
	Exception: STATUS_ACCESS_VIOLATION at eip=0040A108
	eax=14A57719 ebx=0028CBCC ecx=CA12A808 edx=14A57719 esi=80061A8B edi=0028CB98
	ebp=0028CA38 esp=0028CA00 program=C:\Program Files (x86)\360\skylar6\bst\beanstalkd.exe, pid 11164, thread main
	cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
	Stack trace:
	Frame     Function  Args
> 	0028CA38  0040A108 (8006B8A0, 00000000, 00000000, 800630F8)
	0028CAA8  0040ABF9 (0040F120, 00000072, 00000000, 00000001)
	0028CAE8  0040B973 (0040F120, 0028CB10, 0028CB98, 6FB50000)
	0028CBA8  0040D985 (0000000D, 0028CBCC, 800280E8, 61090DD3)
	0028CD28  610084DC (00000000, 0028CD84, 61007520, 00000000)
	End of stack trace
```

4. I disassemble the beanstalkd.exe with objdump.exe, here is some content:
```
	static void
	conn_timeout(Conn *c)
	{
		... ...
	    int r, should_timeout = 0;
	    job j;

	    /* Check if the client was trying to reserve a job. */
	    if (conn_waiting(c) && conndeadlinesoon(c)) should_timeout = 1;
	    ... ...

	    /* Check if any reserved jobs have run out of time. We should do this
	     * whether or not the client is waiting for a new reservation. */
	    while ((j = connsoonestjob(c))) {
	  40a100:	e9 e4 00 00 00       	jmp    40a1e9 <_conn_timeout+0x127>
	        if (j->r.deadline_at >= nanoseconds()) break;
	  40a105:	8b 45 f0             	mov    -0x10(%ebp),%eax
> 	  40a108:	8b 58 30             	mov    0x30(%eax),%ebx
	  40a10b:	8b 70 34             	mov    0x34(%eax),%esi
	  40a10e:	e8 05 19 00 00       	call   40ba18 <_nanoseconds>
	  40a113:	39 d6                	cmp    %edx,%esi
	  40a115:	7c 10                	jl     40a127 <_conn_timeout+0x65>
	  40a117:	39 d6                	cmp    %edx,%esi
	  40a119:	0f 8f e4 00 00 00    	jg     40a203 <_conn_timeout+0x141>
	  40a11f:	39 c3                	cmp    %eax,%ebx
	  40a121:	0f 83 dc 00 00 00    	jae    40a203 <_conn_timeout+0x141>
```

5.  So, I assume the error is happened at instruction "if (j->r.deadline_at >= nanoseconds()) break;" in function "conn_timeout".

I read the beanstalkd code, but I can't figure out why this happened.
Has anyone else experienced this and/or have a solution to the  problem?

Thanks

**Comment by silviucpp** [comment]
I think you posted on a wrong repo. This one is not officially support windows from what I know.

**Comment by ysmolsky** [comment]
Technically it can be compiled under cygwin, but there is not official support there, so the behaviour might a bit weird there.

**Comment by ysmolsky** [comment]
Pls post it here https://github.com/caidongyun/beanstalkd-win. Closing this issue
