### ISSUE TITLE
about HA，any advice?

### ISSUE THREAD

**Issue by JodeZer** [beanstalkd/beanstalkd#344]
we need a system to do crontab tasks that beanstalkd may works ,but this system is asked to be high available and can't loss service ability while it's turned down or just killed.
Any plan on HA cluster  like replication ? Or any advice to implement HA ?

**Comment by JensRantil** [comment]
Given the current implementation, you could always enable WALing and make sure your init process restarts beanstalkd if it crashes.

If you want restarts beyond a single machine, you could mount the same NFS on another machine and run something like [`consul lock beanstalkd ...`](https://www.consul.io/docs/commands/lock.html) on all HA VMs.

**Comment by JodeZer** [comment]
@JensRantil Thanks a lot! 
etcd or ZK ways  happened to have been discussed not long ago.

**Comment by JensRantil** [comment]
Another approach is to to 1) make sure your tasks are idempotent and 2) do double writes to two beanstalkd instances.

I'll be closing this. Let me know if you still have outstanding issues.
