### ISSUE TITLE
There is a doubt about the `use` command in the protocol.

### ISSUE THREAD

**Issue by xuanskyer** [beanstalkd/beanstalkd#347]
There is a doubt about the `use` command in the protocol.

such as multiple `put` commands in the same `connection`, how to ensure that each `put` command is using their own `tube` ( created  by their own `use` command ) ?

**Comment by JensRantil** [comment]
That's not a server issue, it's a client issue. It can easily be solved using the pipeline pattern similar to https://golang.org/pkg/net/textproto/#Pipeline.

**Comment by JensRantil** [comment]
I'm going to close this. Please let me know if still an issues.
