### ISSUE TITLE
Is there a limit on the maximum number of beanstalkd queues?

### ISSUE THREAD

**Issue by xuanskyer** [beanstalkd/beanstalkd#348]
Is there a limit on the maximum number of beanstalkd queues?
If not, does a large number of queues affect performance?

**Comment by JensRantil** [comment]
I can give you a partial answer: Many tubes shouldn't be a problem as long as you don't have too many tubes per subscriber/producer. Each tube is a heap and is very fast.

To be really sure about performance, I suggest you run a benchmark.
