### ISSUE TITLE
beanstalkd[1375]: /usr/bin/beanstalkd: prot.c:1919 in h_accept: accept(): Too many open files

### ISSUE THREAD

**Issue by johnbasinger84** [beanstalkd/beanstalkd#351]
beanstalkd[1375]: /usr/bin/beanstalkd: prot.c:1919 in h_accept: accept(): Too many open files

This error comes after 5 hrs of restarting beanstalkd service..

**Comment by JensRantil** [comment]
Could you please list open files with the lsof command after running för 4 hours to see which files are open? Most certainly, you simply have too many open TCP connections and will want to simply increase the max open file limit for the process.

**Comment by JensRantil** [comment]
See https://github.com/kr/beanstalkd/issues/36#issuecomment-168451 for an expansion of my answer.

**Comment by JensRantil** [comment]
Closing this. Let me know if still an issue.
