### ISSUE TITLE
Not writing logs.

### ISSUE THREAD

**Issue by buntythakkar** [beanstalkd/beanstalkd#354]
I have installed beanstalkd ob ubuntu 16.04 LTS.

Following is my /etc/init.d/beanstalkd config file.

![beanstalk](https://user-images.githubusercontent.com/11338337/26970339-aa6e3d5c-4d26-11e7-9f04-e09eacd6ffe6.png)

As seen the logdir and log

file has been uncommented, but still when i start the beanstalk service, it doesnt write any logs.

Please help. Thanks

**Comment by JensRantil** [comment]
Unfortunately, this Github repository is not the maintainer of the Ubuntu package. I suggest you reach out to the maintainers of the Ubuntu package instead (and close this issue, cc @kr).

Above said, if you start beanstalkd using `-V` you should be getting some logs from it. Also, you could double check that your beanstalkd has been started on your system using verbose logging by issuing something like `ps -ef|grep branstalkd`.

**Comment by Siecje** [comment]
Is it possible to get some logging but not as much as `-V`? 

I don't want to see 

```
beanstalkd: close 15
beanstalkd: accept 7
```

**Comment by JensRantil** [comment]
@Siecje Please open a new issues. Your issue is orthogonal to https://github.com/kr/beanstalkd/issues/354#issue-234776378.

**Comment by mayhewj** [comment]
Ubuntu 16.04 uses `systemd` as the init system and logs are sent to `journald` in the default configuration. You can view the logs using `journalctl -u beanstalkd`.

See `/lib/systemd/system/beanstalkd.service` and `/etc/default/beanstalkd` for configuration.

`/etc/init.d/beanstalkd` is there for those that prefer to run `sysvinit` over `systemd`.

**Comment by JensRantil** [comment]
@kr This issue can now be closed.
