### ISSUE TITLE
binlogs are not getting removed

### ISSUE THREAD

**Issue by raju-divakaran** [beanstalkd/beanstalkd#359]
Hello,

I am maintaining a beanstalk of version 1.4 which will be handling thousands of job per sec. From last few weeks its noticed that the binlogs are not getting removed and this creates problems. In the sense high file system usage. Then one of us have to manually kick jobs and at some point it suddenly comes down.

I read from https://groups.google.com/forum/#!topic/beanstalk-talk/FuXqsoPU_Rg that some orphaned jobs might be causing this. I am sure its same situation, but don't know how to find that job. Can someone help ?

~Raju.

**Comment by JensRantil** [comment]
Could it be that you are hitting https://github.com/kr/beanstalkd/pull/278 ?

**Comment by raju-divakaran** [comment]
I am sorry, we are using version 1.9. I was checking on a wrong server, where an older version was sitting.

So its exactly that, its one job sitting in one of the tube causing it. Today we kicked around 2 million jobs and finally at a point the FS usage came down from 700 GB to 220 GB! I still feel, the usage of 220 GB is also high.

Could a delayed job cause binlogs not be removed ? Would it be some kind of lock that beanstalk fails to keep and ends up creating new bin logs. 

Thanks!
~Raju.

**Comment by JensRantil** [comment]
@raju-divakaran Unfortunately I don't know the internals of beanstalkd to be able to answer that question.

**Comment by ysmolsky** [comment]
@raju-divakaran have you tried to upgrade to 1.10? what is the size of your tubes, e.g how many jobs do you have sitting in the beanstalkd at any given time?

**Comment by ysmolsky** [comment]
I’m closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
