### ISSUE TITLE
1.4.4 Memory Leak?

### ISSUE THREAD

**Issue by pmamediagroup** [beanstalkd/beanstalkd#36]
I keep getting these errors every 10-15 min in dev mode.

beanstalkd: prot.c:1785 in h_accept: accept(): Too many open files
beanstalkd: net.c:72 in brake: too many connections; putting on the brakes

Any ideas?

**Comment by johnbasinger84** [comment]
beanstalkd[1375]: /usr/bin/beanstalkd: prot.c:1919 in h_accept: accept(): Too many open files

This error comes after 5 hrs of restarting beanstalkd service..

**Comment by JensRantil** [comment]
@johnbasinger84 If you cross-post, please mention that you've done so and refer to the other post so other users can track the issue. I've done that for you this time. Thanks.
