### ISSUE TITLE
No package beanstalkd available

### ISSUE THREAD

**Issue by raphaelrosello** [beanstalkd/beanstalkd#360]
Hi,

I was trying to install beanstalkd on AmazonAMI. I'm not sure if there is such kind of my yum is outdated, or do I need to update something to install these because I am totally new with linux environment especially in AmazonAMI.  

**Procedure**
1. Execute yum install beanstalkd

**Expected behavior**
Beanstalkd should be installed

**Actual behavior**
No package **beanstalkd** available

**Comment by JensRantil** [comment]
While I am not a maintainer for beanstalkd, I'm pretty sure that this project tries to avoid packaging for different distributions. It simply doesn't scale to support all of them. Feel free to become a maintainer of beanstalkd YUM package for your favourite Linux distribution if you want to.

**Comment by redhat-raptor** [comment]
For AmazonAMI please enable epel repository. For example:

`vim /etc/yum.repos.d/epel.repo
`
```
[epel]
name=Extra Packages for Enterprise Linux 6 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
```

Note: `enabled=1`

then run:

`yum update`

then should be able to just run: `yum install beanstalkd`

**Comment by JensRantil** [comment]
Closing this. Let me know if still an issue.
