### ISSUE TITLE
Separate binlogs per tube (question)

### ISSUE THREAD

**Issue by ritmas** [beanstalkd/beanstalkd#362]
Is it possible to separate binlogs per tube?
My goal is to sync binlogs of all tubes/jobs except specific ones, e.g. those not so vital in case of server restart.

**Comment by JensRantil** [comment]
No, it's not possible today.

**Comment by JensRantil** [comment]
You can easily run two beanstalkd processes on the same machine listening on different ports, one with wal and one without. I'm going to close this. Let me know if you don't this is a good enough solution.
