### ISSUE TITLE
How do you properly stop beanstalkd?

### ISSUE THREAD

**Issue by Siecje** [beanstalkd/beanstalkd#364]
Version 1.10

When I start `beanstalkd` I get these error messages.

```
/boot/tp/bin/beanstalkd: /boot/dd/jq//binlog.9: unknown version: 0
/boot/tp/bin/beanstalkd: Errors reading one or more WAL files.
/boot/tp/bin/beanstalkd: Continuing. You may be missing data.
```

This is how I am starting `beanstalkd`.

```shell
su -c "/boot/tp/bin/beanstalkd -b /boot/dd/jq/ -f 0 -V | logger -t beanstalkd &" beanstalkd
```

This is with nothing using `beanstalkd`. I'm starting `beanstalkd` on boot. So I see the errors after a `reboot`.

I believe it is because I am not shutting `beanstalkd` down properly.

**Comment by JensRantil** [comment]
Could you try

    su -c "/boot/tp/bin/beanstalkd -b /boot/dd/jq -f 0 -V | logger -t beanstalkd &" beanstalkd

The path doesn't look quite right.

**Comment by Siecje** [comment]
Thanks. I will fix that because of the double slash in the log message. But in Linux paths I don't think multiple slashes matter.

**Comment by JensRantil** [comment]
Better safe than sorry. ;)

Also, have you changed beanstalkd version? Could also be that your binlogs are corrupts or something.

**Comment by Siecje** [comment]
No nothing has used this `beanstalkd`.

**Comment by JensRantil** [comment]
Would it make sense to debug with `strace`? Another idea is to compile an executable with debug symbols and run through `pdb`.

**Comment by JensRantil** [comment]
Closing this. Let me know if still an issue.
