### ISSUE TITLE
What's the proper way to handle DEADLINE_SOON?

### ISSUE THREAD

**Issue by activeshadow** [beanstalkd/beanstalkd#366]
I've read [this post](https://groups.google.com/forum/#!topic/beanstalk-talk/Iy0MrFvr4w8) through and through, and I'm still not sure how to handle `DEADLINE_SOON` in my use case, or if it's even possible.

I have a Go program that uses a dispatcher to reserve jobs from Beanstalk and pass them on to a pool of workers running in Goroutines. As such, the dispatcher reserves job after job as fast as possible, and since the jobs get passed on to the next available worker the dispatcher doesn't know what job is about to expire when it receives a `DEADLINE_SOON` error from the reserve call.

Does the Beanstalk server by chance include the ID of the job that's about to expire when it sends `DEADLINE_SOON` and I'm just overlooking that in the documentation? If not, any suggestions on how to handle `DEADLINE_SOON` given my use case? Perhaps I just need to let each of the workers in the pool maintain their own client connection to the server?

**Comment by JensRantil** [comment]
> Does the Beanstalk server by chance include the ID of the job that's about to expire when it sends DEADLINE_SOON and I'm just overlooking that in the documentation?

Unfortunately the ID is not included.

Some quick ideas:

 * Increase your TTR to avoid DEADLINE_SOON.
 * Periodically `touch` your job when you are processing it to extend the TTR.

> Perhaps I just need to let each of the workers in the pool maintain their own client connection to the server?

Yes, either that, or you could use something like https://golang.org/pkg/net/textproto/#Pipeline to pipeline/mux multiple requests through a single TCP connection.
