### ISSUE TITLE
what does it mean to keep on getting kicked out of beanstalk? 🤔

### ISSUE THREAD

**Issue by abbood** [beanstalkd/beanstalkd#371]
# Background
we used [Laravel Queues][1] on top of [beanstalkd][2] on two ec2 instances (behind a load balancer). our AWS ec2 instances are auto provisioned using [forge][2], including the supervisor that makes sure that beanstalk is always running.

with beanstalkd, I used [beanstalk utilities][3] to monitor the health of the queue.. for example if the queue was getting clogged, I could easily see that by running a command like this:

    ./beanstalk-queue-stats.rb localhost:11300

which would return something like this

    2018-01-10 11:08:38 +0000
    default
     - cmd-delete = 32678 (+32678)
     - cmd-pause-tube = 0 (0)
     - current-jobs-buried = 0 (0)
     - current-jobs-delayed = 0 (0)
     - current-jobs-ready = 0 (0)
     - current-jobs-reserved = 0 (0)
     - current-jobs-urgent = 0 (0)
     - current-using = 5 (+5)
     - current-waiting = 0 (0)
     - current-watching = 2 (+2)
     - pause = 0 (0)
     - pause-time-left = 0 (0)
     - total-jobs = 32678 (+32678)
    high
     - cmd-delete = 116005 (+116005)
     - cmd-pause-tube = 0 (0)
     - current-jobs-buried = 0 (0)
     - current-jobs-delayed = 9 (+9)
     - current-jobs-ready = 1117 (+1117)
     - current-jobs-reserved = 0 (0)
     - current-jobs-urgent = 0 (0)
     - current-using = 0 (0)
     - current-waiting = 0 (0)
     - current-watching = 1 (+1)
     - pause = 0 (0)
     - pause-time-left = 0 (0)
     - total-jobs = 117131 (+117131)
    low
     - cmd-delete = 0 (0)
     - cmd-pause-tube = 0 (0)
     - current-jobs-buried = 0 (0)
     - current-jobs-delayed = 0 (0)
     - current-jobs-ready = 0 (0)
     - current-jobs-reserved = 0 (0)
     - current-jobs-urgent = 0 (0)
     - current-using = 0 (0)
     - current-waiting = 0 (0)
     - current-watching = 1 (+1)
     - pause = 0 (0)
     - pause-time-left = 0 (0)
     - total-jobs = 0 (0)
    marketing
     - cmd-delete = 0 (0)
     - cmd-pause-tube = 0 (0)
     - current-jobs-buried = 0 (0)
     - current-jobs-delayed = 0 (0)
     - current-jobs-ready = 0 (0)
     - current-jobs-reserved = 0 (0)
     - current-jobs-urgent = 0 (0)
     - current-using = 0 (0)
     - current-waiting = 0 (0)
     - current-watching = 1 (+1)
     - pause = 0 (0)
     - pause-time-left = 0 (0)
     - total-jobs = 0 (0)
    ------------------

etc. (see related question [here][1])

the problem is that I keep on getting kicked out of beanstalk with this error

    /home/forge/.rvm/gems/ruby-2.4.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:212:in `check_resp': NOT_FOUND (Beanstalk::NotFoundError)
    	from /home/forge/.rvm/gems/ruby-2.4.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:231:in `read_yaml'
    	from /home/forge/.rvm/gems/ruby-2.4.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:195:in `interact'
    	from /home/forge/.rvm/gems/ruby-2.4.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:173:in `stats_tube'
    	from ./beanstalk-queue-stats.rb:21:in `block (2 levels) in <main>'
    	from ./beanstalk-queue-stats.rb:19:in `each'
    	from ./beanstalk-queue-stats.rb:19:in `block in <main>'
    	from ./beanstalk-queue-stats.rb:17:in `loop'
    	from ./beanstalk-queue-stats.rb:17:in `<main>'

this happens on both instances. 
I checked the workers on forge.. and they seem to be fine:

    worker-157645:worker-157645_00   RUNNING   pid 10110, uptime 0:25:47
    worker-157646:worker-157646_00   RUNNING   pid 10236, uptime 0:25:44
    worker-157647:worker-157647_00   RUNNING   pid 10336, uptime 0:25:42
    worker-157648:worker-157648_00   RUNNING   pid 10472, uptime 0:25:36

and more importantly, the pid is not changing (I would assuem the pids would change everytime beanstalk crashes.. but it seems it's not)

and needless to say, this is messing up our system as the jobs that are supposed to be processed in the queue are sometimes working, sometimes not working, sometimes take a while to work..

any ideas?

**Comment by mkopinsky** [comment]
"Kick" in beanstalkd is actually a specific command in the protocol, to move a job from Buried status back to Ready. It's not related to this issue - I only mention it to disambiguate in case other people come across this issue Googling.

There isn't really enough info here to know what's going on. I would suggest running beanstalkd with the `-V` (verbose) flag - that might give some info. I would also suggest opening an issue with the beanstalkd-client maintainers - they're far more likely to know what that specific error means.

**Comment by JensRantil** [comment]
@abbood Could it be your AWS load balancer (running in TCP mode I assume?) closes connections if there isn't any traffic going through for a while? Since beanstalkd hasn't restarted I don't see anything hinting that this is a beanstalkd problem. I'll be closing this issue. Let me know if I should reopen - if so, I'd appreciate if you could point to anything in beanstalkd being broken (best scenario: Recreate a problem locally).
