### ISSUE TITLE
beanstalkd cannot be built on Windows

### ISSUE THREAD

**Issue by atefBB** [beanstalkd/beanstalkd#376]
I run `make` command and I got `process_begin: CreateProcess(NULL, cc dat.h sd-daemon.h -o .o, ...) failed.`.
I'm using win7 x64.
Help plz. Thanks.

**Comment by ysmolsky** [comment]
@atefBB beanstalkd does not support Windows right now, only Linux, OSX and FreeBSD.

**Comment by ysmolsky** [comment]
And we have no plans to add such a support at this moment. You could try to use beanstalkd via mingw I guess, but I never tried. Let me know if that worked out for you.

**Comment by atefBB** [comment]
@ysmolsky Thank you !

**Comment by ysmolsky** [comment]
I will keep this kind of issues open so that others can find them. Also we would know on which platforms beanstalkd is wanted.

**Comment by ysmolsky** [comment]
Windows support is not planned at all, so closing.
