### ISSUE TITLE
[Question] Why delete command throws NOT_FOUND for READY/RESERVED job?

### ISSUE THREAD

**Issue by StalkAlex** [beanstalkd/beanstalkd#377]
My question from protocol description for delete command:
```
The client then waits for one line of response, which may be:

 - "DELETED\r\n" to indicate success.

 - "NOT_FOUND\r\n" if the job does not exist or is not either reserved by the
   client, ready, or buried. This could happen if the job timed out before the
   client sent the delete command.
```
Why server returns NOT_FOUND for timed out job? In my case TTR was less then real time of a job, so before first worker returned DELETE, job become available again. It gets READY state, then in my case I have several parallel workers and another worker reserves this job and it becomes RESERVED. In that moment first worker returns DELETE, but job is not removing, instead I get NOT_FOUND and endless loop of generating many files(this is my job meaning), until new other job gets in the tube. Why this is working like this? 

Job has READY state, then RESERVED and first sentence of not found description says that it's not a problem to delete.

**Comment by ptjm** [comment]
What the text you cite says is that NOT_FOUND will be returned if the job is reserved by another client. It needs to be either ready, buried, or reserved by the client which is trying to delete it.

If you have jobs which are regularly timing out before they complete, you need to deal with that somehow, e.g., give more time to start with, or recognize when time is getting short and extend it in the reserving job, or reverse the effects of the original job when it times out, or check the age of the job and perform some kind of end-of-life processing when it gets too old.

**Comment by StalkAlex** [comment]
> It needs to be either ready, buried, or reserved by the client which is trying to delete it.

What prevents from removing if it has reserved by another client?

**Comment by ptjm** [comment]
It's to the client which reserves the job is guaranteed the job will still be there until it times out.

**Comment by JensRantil** [comment]
Closing this. Let me know if your question hasn't been answered.
