### ISSUE TITLE
reserved job is not released when ttr has ended (time-left < 0)

### ISSUE THREAD

**Issue by bryanlarsen** [beanstalkd/beanstalkd#380]
I was under the impression from the documentation that this state was impossible.   If time-left is negative, then state should be "ready", not reserved.

We're using fivebeans as a client.   This bug does not occur consistently, but it does occur frequently in our app.   I'm trying to reproduce using an expect script, but it's proving difficult.

id | 1730
tube | render-v2-webgl
state | reserved
pri | 10000
age | 661
delay | 0
ttr | 60
time-left | -306
file | 1
reserves | 2
timeouts | 1
releases | 0
buries | 0
kicks | 0

**Comment by ysmolsky** [comment]
@bryanlarsen do you touch the job from the client? Can you show the code which produces this?

**Comment by ysmolsky** [comment]
Most likely related issue is #262 that has an outstanding fix and some debugging info.

**Comment by ysmolsky** [comment]
I’m closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
