### ISSUE TITLE
请问最新稳定版使用哪个版本

### ISSUE THREAD

**Issue by lagolas** [beanstalkd/beanstalkd#381]
release上最后一次是2014年的v1.10。我看到master还有继续更新，请问最新稳定的使用v1.10版还是master分支？谢谢！

**Comment by JensRantil** [comment]
Please track https://github.com/kr/beanstalkd/issues/299 for the activity of this rather dead project. I'd suggest you start using the `master` branch as it contains a few bugfixes which are not part of the release.

**Comment by kr** [comment]
那是个很好的观点。 我应该发布一个新版本。

**Comment by JensRantil** [comment]
Please see #383.
