### ISSUE TITLE
prot.c: null dereference in enqueue_reserved_jobs

### ISSUE THREAD

**Issue by PatriciaSVMonteiro** [beanstalkd/beanstalkd#384]
I'm using Infer to analise the code of the latest version of Beanstalkd. The tool found the following error:

```
pointer `j` last assigned on line 509 could be null and is dereferenced by call to `enqueue_job()` at line 510, column 13.
  508.       while (job_list_any_p(&c->reserved_jobs)) {
  509.           j = job_remove(c->reserved_jobs.next);
  510. >         r = enqueue_job(c->srv, j, 0, 0);
  511.           if (r < 1) bury_job(c->srv, j, 0);
  512.           global_stat.reserved_ct--;
```
This error occurs because the value of the job_remove function is not checked before it is used, and it can return NULL in two situations:
1 - When the argument passed to the job_remove is NULL;
2 - When the value returned by the job_list_any_p is NULL.
Therefore, the value of the variable j must be checked before being passed to the enqueue_job function. In the enqueue_job function, a dereference is made of j, so if j is NULL this error will cause undefined behavior of the program.

**Comment by JensRantil** [comment]
Hi @PatriciaSVMonteiro! Nice find! Would you be interested in submitting a pull request to fix this?

**Comment by ysmolsky** [comment]
Job cannot be NULL when passed to `enqueue_job` because `job_remove` won't return NULL because `job_list_any_p` has returned non-NULL value. This code could be more simple I agree and  right now it looks like so:
```c
void
enqueue_reserved_jobs(Conn *c)
{
    while (!job_list_is_empty(&c->reserved_jobs)) {
        Job *j = job_list_remove(c->reserved_jobs.next);
        int r = enqueue_job(c->srv, j, 0, 0);
        if (r < 1)
            bury_job(c->srv, j, 0);
        global_stat.reserved_ct--;
        j->tube->stat.reserved_ct--;
        c->soonest_job = NULL;
    }
}
```
The code for double-linked lists is hard to reason about in general.
