### ISSUE TITLE
project maintenance going forward?

### ISSUE THREAD

**Issue by petri** [beanstalkd/beanstalkd#385]
While beanstalkd is mature software, there is always need for some love as evidenced by the number of long-standing open issues and PRs.

@kr would you have any suggestions as to what the community could and/or should do? Is there anything you think you could do to support or facilitate that?

Thank you.

**Comment by pmatseykanets** [comment]
#335

**Comment by pprindeville** [comment]
Related #383

**Comment by pprindeville** [comment]
What about adding a 2nd maintainer who has a long-standing involvement in the project and the author trusts?

**Comment by JensRantil** [comment]
I believe this is a duplicate of #299.

**Comment by JensRantil** [comment]
Closing this. The original maintainer, @kr, has added me as an additional maintainer.
