### ISSUE TITLE
Switch over go beanstalk client repo to new org

### ISSUE THREAD

**Issue by tomponline** [beanstalkd/beanstalkd#390]
@JensRantil is it possible to also get the Golang beanstalk client repo moved over also from @kr 
https://github.com/kr/beanstalk

As I have some outstanding patches on it that would be great to merge, so I can switch back to upstream from my own fork.

https://github.com/kr/beanstalk/pull/26

**Comment by JensRantil** [comment]
I think that's a great idea. I have reached out to Keith over e-mail and will get back here as soon as I get a response from him regarding this.

**Comment by JensRantil** [comment]
Keith responded to me yesterday and transferred it to the organization. 🎉

To make it clear that it was a go client repo, I changed the repo name from "beanstalk" to "go-beanstalk" (added dash to avoid conflict with https://github.com/iwanbk/gobeanstalk). Let me know if you think that was a bad idea or if you have a better naming for it.

I'll try to get to review https://github.com/beanstalkd/go-beanstalk/pull/26 today.

**Comment by JensRantil** [comment]
Note to self: This issue came out of https://github.com/beanstalkd/beanstalkd/issues/299#issuecomment-413848926.

**Comment by tomponline** [comment]
@JensRantil sounds good on the rename of the repo cheers
