### ISSUE TITLE
Less verbose logging

### ISSUE THREAD

**Issue by Siecje** [beanstalkd/beanstalkd#397]
Is it possible to get some logging but not as much as `-V`? 

I don't want to see 

```
beanstalkd: close 15
beanstalkd: accept 7
```

**Comment by sergeyklay** [comment]
Yeah, it's looks like DEBUG mode

**Comment by Siecje** [comment]
How do you disable DEBUG mode?

**Comment by sergeyklay** [comment]
@Siecje Please provide the used way to start beanstalkd with all options

**Comment by Siecje** [comment]
```shell
beanstalkd -b /boot/dd/jq/ -f 0 -V
```

**Comment by ysmolsky** [comment]
@Siecje what kind of messages would you like to see in -V mode?

**Comment by Siecje** [comment]
I don't use beanstalkd anymore. Are there other messages besides the close and accept connections?

**Comment by ysmolsky** [comment]
Thanks. I do not see a point to reduce the current level of verbosity for -V. That is to show accept, close and bind events. There is nothing to show less than that.
