### ISSUE TITLE
create a 1.11 release to include the commits since 1.10

### ISSUE THREAD

**Issue by tomponline** [beanstalkd/beanstalkd#399]
Hi @JensRantil I wondered if it was possible to create a 1.11 release of beanstalkd, to include the commits already in master since 1.10.

https://github.com/beanstalkd/beanstalkd/compare/v1.10...master

**Comment by ysmolsky** [comment]
It's very unfortunate that such a great piece of software is abandoned. Yes, there are commits here and there and there was no proper release for more than 4 years. To make this more constructive. 

@JensRantil, what help do you need to make new releases possible?

**Comment by tomponline** [comment]
I've not heard from @JensRantil since a few days after he rested the beanstalk project away from @kr

**Comment by stamster** [comment]
@tomponline so this starts to look like a House of the Damned? :) Hope not and everyone are OK.

**Comment by L3o-pold** [comment]
@JensRantil Could you tag the new release please?

**Comment by tomponline** [comment]
@JensRantil would you be able to give me access to the beanstalk org to avoid a fork? thanks

**Comment by stamster** [comment]
https://github.com/gocql/gocql/pull/1236

**Comment by tomponline** [comment]
@stamster what was that link about?

**Comment by kaspergrubbe** [comment]
@tomponline Just to show that the maintainer hasn't disappeared (thankfully!).

**Comment by tomponline** [comment]
@kr would you be willing to create a new tag release of master? Thanks

**Comment by dontub** [comment]
Looks like a fork is unavoidable...

**Comment by sergeyklay** [comment]
@JensRantil Can we hope for release next version?

**Comment by sergeyklay** [comment]
ping @JensRantil

**Comment by jsabater** [comment]
There are 747 forks already. Has anyone heard back from @JensRantil or @kr? Is a new 1.11 version with the commits since 1.10 expected or available anywhere else?

**Comment by kaspergrubbe** [comment]
Maybe it's time for a proper community project fork? :( 

Not sure who would be the best candidate for maintaining it, but maybe it's not that important, as long as it is some that knows a bit about the codebase, can make releases and is reachable.

**Comment by kaspergrubbe** [comment]
@alup @kr @nesquena @nicotaing @petri @tdg5 @vit1251 Sorry for tagging you, but you all seem to be part of the beanstalkd Github organisation, could we start a search for maintainers, so that we can pass the torch on?

I would like to help with the efforts of searching if you give me the permissions to do so.

**Comment by vit1251** [comment]
@kaspergrubbe I am sorry TL;DR that topic but I can help with debian packager (only technical issue no connection with debian community) if you want modern deb package.

**Comment by allenwu1973** [comment]
@kr @JensRantil We, like many others, use beanstalkd in production. Is there any way we can help to make  a new release?

**Comment by tomponline** [comment]
@ysmolsky are you happy to move forward on this issue now?

**Comment by ysmolsky** [comment]
Yes, I am. I started looking at old issues and PRs, but I think that we should release before anything else and get feedback on that.

**Comment by jsabater** [comment]
I think that the best course of action is what you proposed, @ysmolsky: release version 1.11 with what has been committed since 1.10, then start bringing more in while getting feedback. Thanks in advance.

**Comment by ysmolsky** [comment]
I am rehearsing the release by following the guide here: https://github.com/beanstalkd/beanstalkd/tree/master/pkg
```
1. Check out master
2. Tag the commit to release devX.Y (e.g. dev1.9)
3. Write a change log in file News (don't commit it)
4. Run pkg/dist.sh
5. Push tags and gh-pages
6. Run pkg/mail.sh
```
I have tagged the latest commit as dev1.11 with some foobar message. 
Wrote some foobar News files.
But I got stuck on the step of running pkg/dist.sh:
```sh
$ pkg/dist.sh
fatal: 6d77332ce8c8c9675d058eef2165b078b592802d is not a valid 'commit' object
```
With debugging output turned on the culprit line is:
```
commit=`git commit-tree $tree -p dev$ver -m "release $ver"`
```
https://github.com/beanstalkd/beanstalkd/blob/master/pkg/dist.sh#L41

**Comment by ysmolsky** [comment]
I am rehearsing the release by following the guide here: https://github.com/beanstalkd/beanstalkd/tree/master/pkg
```
1. Check out master
2. Tag the commit to release devX.Y (e.g. dev1.9)
3. Write a change log in file News (don't commit it)
4. Run pkg/dist.sh
5. Push tags and gh-pages
6. Run pkg/mail.sh
```
I have tagged the latest commit as dev1.11 with some foobar message. 
Wrote some foobar News files.
But I got stuck on the step of running pkg/dist.sh:
```sh
$ pkg/dist.sh
fatal: 6d77332ce8c8c9675d058eef2165b078b592802d is not a valid 'commit' object
```
With debugging output turned on the culprit line is:
```
commit=`git commit-tree $tree -p dev$ver -m "release $ver"`
```
https://github.com/beanstalkd/beanstalkd/blob/master/pkg/dist.sh#L41

Also down the file I see reference to refs/heads/gh-pages, but there are no branches of this kind in this repo.

@kr, can you explain what is going on here? :)

**Comment by ysmolsky** [comment]
First issues is figured out. Line 41 should be this:
```
commit=`git commit-tree -p dev$ver -m "release $ver" $tree`
```
This allows the creation of release branch tagged 1.11.

@kr what is the rationale behind dev* tags? Did you do release of dev branch first directly via Github? I am confused because I see releases like dev1.10 on github.

As for gh-pages, it seems to me that this was a branch in this repo that contained the blog, but it was moved away into separate repo.

**Comment by kr** [comment]
I was never totally happy with the release process. I fiddled with it a few times and eventually settled on this. I had a couple of goals:

- avoiding hard-coding the version number in source code in the main branch, since that produces misleading output for every commit other than the actual release commit
- still having the release tarball contain the version string so it can build correctly (of course)
- being able to distribute the release directly from github using their tarball links

Making a little one-commit branch for each release let me do all of those things.

This all happened before github had a notion of releases, so I'm sure there is a better way now. Definitely feel free to change anything about this process if you want.

> @kr what is the rationale behind dev* tags? Did you do release of dev branch first directly via Github? I am confused because I see releases like dev1.10 on github.

I think github creates "releases" for tags automatically.

The only purpose of the dev* tags is to make it easy to know when releases happened on the main branch, for e.g. bisecting and scripting.

**Comment by kr** [comment]
> The only purpose of the dev* tags is to make it easy to know when releases happened on the main branch, for e.g. bisecting and scripting.

For example, vers.sh uses the dev tags to print an accurate version string for whatever commit you happen to be on.

**Comment by tomponline** [comment]
@ysmolsky im happy if you want to proceed with 1.11 release BTW 😃

**Comment by ysmolsky** [comment]
Uhm, I thought that you wanted to try to release next version. Surely I can do it, but I would rather not since everything is done by me right now. I don’t want to be a single point of failure. Can you try to do it, report what is not working or not clear, and then if you are stuck for good, I can take over? Also I can review changes/news before pushing tags and posts. What concerns do you have?

**Comment by tomponline** [comment]
@ysmolsky I am still happy to try it, and agree it would be good to have more than 1 person able to do it. I just didn't want to hold you up if you had time available to do it. I'm hoping to get a bit of time at the weekend to try this though :)

**Comment by tomponline** [comment]
@kr how thorough would you say the unit tests are and what is the way to run them? I'd like to checkout the master and run the tests before tagging just to make sure there are no obvious issues. Thanks

**Comment by ysmolsky** [comment]
I have no rush with this. I will wait. Especially that I had a day off and was able to batch some work on beanstalkd. And now I have to take a break until the weekend.

**Comment by kr** [comment]
> @kr how thorough would you say the unit tests are and what is the way to run them?

To run them, it's `make check`.

I would say their thoroughness is okay but not great. Most of the existing tests are exercising various error conditions (like disk full) and the basic data structures (like the binary heap).

**Comment by tomponline** [comment]
This is now done!

https://github.com/beanstalkd/beanstalkd/compare/v1.10...v1.11

Thanks @kr and @ysmolsky and everyone who contributed to it. :)

**Comment by ysmolsky** [comment]
@tomponline we forgot about making an announcement in https://groups.google.com/forum/#!forum/beanstalk-talk

There is a script in `pkg`, but I have not tested it myself.

**Comment by tomponline** [comment]
@ysmolsky will take a look thanks.

**Comment by kaspergrubbe** [comment]
Yo! Thanks for your efforts towards a `1.11`-release!

**Comment by stamster** [comment]
I believe Debian and/or other package maintainers shall be notified about new release.

These are results from current Ubuntu LTS distro release:

```
Package: beanstalkd
Version: 1.10-4
Priority: extra
Section: universe/net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Gregory Potamianos <greg.potamianos@gmail.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 117 kB
Depends: libc6 (>= 2.14), libsystemd0, init-system-helpers (>= 1.18~), adduser, netbase, lsb-base (>= 3.0-6)
Suggests: doc-base
Homepage: https://kr.github.com/beanstalkd/
Download-Size: 43.0 kB
APT-Sources: http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
Description: simple, in-memory, workqueue service
 Beanstalkd is a simple, fast, workqueue service (a specific case of message
 queueing), in which messages are organised in "tubes". Beanstalk clients can
 insert and consume messages into and from such tubes.
 .
 The beanstalk interface is generic, but was originally designed for reducing
 the latency of page views in high-volume web applications by running
 time-consuming tasks asynchronously.
 .
 Beanstalkd is meant to be ran in a trusted network, as it has no
 authorisation/authentication mechanisms.
 .
 This package has the server files.
```

**Comment by ysmolsky** [comment]
@stamster what is the best way? is writing to https://groups.google.com/forum/#!forum/beanstalk-talk enough?

**Comment by tomponline** [comment]
@ysmolsky I'm going to do that tonight btw

**Comment by tomponline** [comment]
Alpine linux already picked it up: https://pkgs.alpinelinux.org/packages?name=beanstalkd&branch=edge

**Comment by tomponline** [comment]
Post to group is live https://groups.google.com/forum/#!topic/beanstalk-talk/qdWVZcUOvQg
