### ISSUE TITLE
Unexpected/inconsistent behaviour when combining delay and pri.

### ISSUE THREAD

**Issue by stoodfarback** [beanstalkd/beanstalkd#400]
Scenario: I want to run two jobs, same delay, different priorities.
I want them to be processed in the order based on priority.
The jobs are processed in the order they were inserted instead.

To demonstrate:

A simple consumer that just prints out the job body:
```ruby
beanstalk = Beaneater.new("localhost")
beanstalk.jobs.register("default") {|job| puts(job.body) }
beanstalk.jobs.process!
```

In another window:
```ruby
beanstalk = Beaneater.new("localhost")
tube = beanstalk.tubes.find("default")
tube.put("should be second", delay: 3, priority: 20)
tube.put("should be first", delay: 3, priority: 10)
```

Expected:
```
should be first
should be second
```

Actual:
```
should be second
should be first
```

As a workaround, I've found that adding a junk job first (with the same delay) gets the jobs in the correct order:
```ruby
beanstalk = Beaneater.new("localhost")
tube = beanstalk.tubes.find("default")
tube.put("junk", delay: 3, priority: 20)
tube.put("should be second", delay: 3, priority: 20)
tube.put("should be first", delay: 3, priority: 10)
```

Outputs:
```
junk
should be first
should be second
```

Alternatively, pausing the entire tube instead of using delays on the jobs also works.
But that doesn't fit for my use-case.

**Comment by kr** [comment]
Each job in your example is delayed for 3 seconds, but you submitted the "should be second" job a moment before the other job. That means its delay expires a moment earlier. At that instant, only one job is ready. So the worker picks up that one. Then the other job's delay runs out and it becomes ready, and the worker runs that one.

**Comment by kr** [comment]
When the worker gets the "junk" job first, it takes it some time to process that job. It happens that in your configuration, that is enough time for both other jobs' delays to expire, and they both become ready. Then, when the worker is finished with the junk job, it issues a "reserve" command. At that instant 2 jobs are ready. So it picks up the one with the more urgent priority first.

**Comment by stoodfarback** [comment]
Thank you for the explanation, that makes sense.
Probably not a bug, just me not understanding how the delay worked, so I'm closing the issue.
Do you know if pausing the tube will work reliably, or if that only worked for weird timing reasons too?

**Comment by kr** [comment]
Pausing the tube should do what you're looking for. All jobs submitted while the tube is paused will simultaneously become ready when you un-pause it.

**Comment by stoodfarback** [comment]
Perfect, thanks again for your help.
