### ISSUE TITLE
Q: Does DELETE command works on a timed out job?

### ISSUE THREAD

**Issue by nikolaposa** [beanstalkd/beanstalkd#402]
Scenario:
1. job is reserved by a worker
2. worker reserved a job for more than `ttr` seconds
3. beanstalkd timeouts the job and releases it (puts it into the ready state)
4. worker eventually completes its work and tries to acknowledge (delete) the job

What I don't understand is whether `DELETE` command will have an effect if called on the job that has jut timed out?

**Comment by ifduyue** [comment]
https://github.com/beanstalkd/beanstalkd/blob/b5a6f7a23a368ffb31fbf48cdffe95541166d3fa/prot.c#L1341-L1345

Yes, it will delete this job, unless this job was reserved by another connection.

**Comment by ysmolsky** [comment]
@nikolaposa does this answer your question?

**Comment by nikolaposa** [comment]
@ysmolsky Yes, it does, feel free to close this issue.

**Comment by ysmolsky** [comment]
@nikolaposa thanks, but I can't. Perhaps, you, as author of the bug, can close it?
