### ISSUE TITLE
 Beanstalk ('delete', 'NOT_FOUND', [])

### ISSUE THREAD

**Issue by SumedhaJagtap** [beanstalkd/beanstalkd#405]
Do multiple receivers can cause such situations?

**Comment by ysmolsky** [comment]
Yes, multiple connections can cause this. When connection A has reserved the job and connection B tries to delete it, connection B will see the NOT_FOUND response.

**Comment by SumedhaJagtap** [comment]
Does it mean that multiple queues can reserve the same job?
Is it a good functionality because we are going to execute 100 receivers for one queue?

**Comment by ysmolsky** [comment]
Thank you @karimsan , that is a good explanation.
