### ISSUE TITLE
Get pause delay?

### ISSUE THREAD

**Issue by robertology** [beanstalkd/beanstalkd#406]
I've just recently discovered the pause-tube command. For my use case, I want to pause it briefly, then unpause (set delay to zero) but I don't necessarily want to change the delay value if someone else has paused it.

Is there a way to get the current delay? Or at a minimum to see if there is a delay currently set?

**Comment by ifduyue** [comment]
https://github.com/beanstalkd/beanstalkd/blob/b5a6f7a23a368ffb31fbf48cdffe95541166d3fa/prot.c#L192-L207

Use `stats-tube`, `pause` and `pause-time-left` are what you're look for.

**Comment by robertology** [comment]
That's it. Thanks!
