### ISSUE TITLE
How to cancel a RESERVE command without disconnecting the client

### ISSUE THREAD

**Issue by apmcodes** [beanstalkd/beanstalkd#407]
Since RESERVE command is blocking, nodejs client libraries (fivebeans/ beanstalkd) are not able to sent any further watch/ ignore or other commands. The other commands just hang. 

The requirement is to be able to dynamically watch/ ignore tubes in a single existing client connection. 
Is there a way to cancel the current RESERVE call and free the client?

**Comment by ptjm** [comment]
If you have some external process or thread that is initiating this, you can have it put a message on one of the tubes that's already watched. If you want to poll, you can use reserve-with-timeout with the timeout period set to your poll interval.

**Comment by ysmolsky** [comment]
The architecture of beanstalkd does not allow to reserve while sending other commands at the same time. Please refer to the protocol and find the reserver-with-timeout as mentioned by @ptjm.
@apmcodes I hope that the answer above was satisfactory. Please open if you have further questions.
