### ISSUE TITLE
Wrote a client library for Node

### ISSUE THREAD

**Issue by divmgl** [beanstalkd/beanstalkd#408]
Hello. I wrote a client library for Node. I'm going to be using it for a big deployment in the coming days so I plan on maintaining it as I find issues. Feel free to add it to the Wiki if you feel that it's up to your standards. Appreciate it.

https://github.com/getjackd/jackd

**Comment by ysmolsky** [comment]
Closing as I see, that your lib is already listed here: https://github.com/beanstalkd/beanstalkd/wiki/Client-Libraries
