### ISSUE TITLE
how to modify reverse ttr time?

### ISSUE THREAD

**Issue by jjnha** [beanstalkd/beanstalkd#409]
After reverse() a job,  I didn't use bury(), release(), delete() to set the job state Immediately , first to judge a business logic, if it fails, I will use bury() setting  the job priority to execute again, but I found the business logic is not finished , the  reverse job became the ready state quickly(in a few minute? ), the process has been repeatedly got the job task,  how can I modify the  reverse () ttr time ? Or is there any better way to handle it?

**Comment by ifduyue** [comment]
https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L139-L144
https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L309-L326

**Comment by ysmolsky** [comment]
Yes, when the job is put, the TTR (time to run) can be specified with it. Or you can touch the job periodically to prolong the processing of the job.
