### ISSUE TITLE
add SASL support

### ISSUE THREAD

**Issue by kr** [beanstalkd/beanstalkd#41]

**Comment by JensRantil** [comment]
> @kr Would this feature still be welcome?

Ping @kr.

> beanstalkd is awesome. but we are unlikely to use it in production due to the lack of access control to the service and to individual tubes.

@emmeljay Workaround are to encrypt your job bodies, use stunnel and/or harden traffic using firewalls.

**Comment by ysmolsky** [comment]
I recommend to use stunnel to solve this problem.
