### ISSUE TITLE
consider adding active maintainers

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#413]
@kr, would you consider the idea of adding more maintainers to the project?

There are lots of requests for a release and there are many outstanding bugs in the beanstalkd. Some use it in production because it's fast and capable, but there are critical bugs for which people has to use workarounds and crutches. Users, me included, love this server and want to make it even better.

I understand that you are busy and maybe lost interest, but please find some time to pass the torch to somebody who still cares.

Thank you.

CC: @JensRantil

**Comment by kr** [comment]
> please find some time to pass the torch

My apologies, I thought I had already done that.

I'm happy to add more folks to the github org if anyone else wants to take on maintenance tasks.

I'll also remove myself from the github org on July 1st, to help avoid further confusion.

**Comment by tomponline** [comment]
@kr id be happy to help in this

**Comment by ysmolsky** [comment]
@kr, if my email has not reached you...
I would be glad to help with beanstalkd too.

**Comment by kr** [comment]
Side note to any new maintainers. There is some minimal documentation on the release procedure for beanstalkd in the readme in https://github.com/beanstalkd/beanstalkd/tree/master/pkg. It's not much but better than nothing.

**Comment by tomponline** [comment]
Thanks @kr I will take a look

**Comment by kr** [comment]
I just invited @tomponline and @ysmolsky to the org.

**Comment by ysmolsky** [comment]
Thank you, @kr. One thing. As a member of this org, I am not able to manage tickets or PR's. I think the rights of members are very much restricted.

**Comment by tomponline** [comment]
@kr I only appear to be a member not owner like the others. Thanks

**Comment by kr** [comment]
Sorry about that, I will try to fix it now.

**Comment by kr** [comment]
Hopefully it is fixed for you two now. I often have trouble understanding GitHub's permissions. Sorry again!

**Comment by tomponline** [comment]
thanks @kr that seems good now. :)

**Comment by kr** [comment]
Thank you so much for taking on this work, and to the whole community for being so nonjudgemental and supportive. ❤️

**Comment by ysmolsky** [comment]
Thank you, Keith.
