### ISSUE TITLE
make labels useful for triaging issues

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#415]
Right now the set of labels is not useful. I propose to remove all the labels and create the following set shamelessly borrowed from Go issue trackers (since I know that by heart):

* Help Wanted - Community is welcome to help with fixing the issue. Might be a good issue for novices.
* Documentation - The required fix is about fixing documentation only.
* Question - Author of an issue seeks help, it will not lead to the changes of the code.
* NeedsInvestigation - Someone must examine and confirm this is a valid issue and not a duplicate of an existing one.
* NeedsDecision - Feedback is required from experts, contributors, and/or the community before a change can be made.
* NeedsFix - The path to resolution is known, but the work has not been done.
* WaitingForInfo - Issue is not actionable because of missing required information, which needs to be provided.

This set of active, strong labels suggesting the next step for the community.

**Comment by ysmolsky** [comment]
ping @tomponline @JensRantil

**Comment by tomponline** [comment]
@ysmolsky I'm happy with these.

**Comment by ysmolsky** [comment]
Great. I have applied these new labels. Please start using them when triaging the issues.
