### ISSUE TITLE
all: reduce complex lines in the code

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#442]
Don't get me wrong. I like the most of the style adopted in beanstalkd. There are some things that can be improved:

1. `return`'s on the same line as `if`. They are common. `return` should start a new line always.
```
    if (!c->out_job) return reply_serr(c, MSG_OUT_OF_MEMORY);
[skip]
    if (r > stats_len) return reply_serr(c, MSG_INTERNAL_ERROR);
```
2. Comma expressions in returns. Comma expressions. Not so common. Do not use comma expression where multiple lines can do.
```
if (some) twarnx("..."), return expression;
```
I prefer to read the code vertically, but this style makes by eyes bleed because I have to read the code in double columns. I hope that you agree with me and we can fix the code little by little, moving forward, or at least not add mode code in this style.

I prefer verbose clarity rather than obscure smartness.

@tomponline @sergeyklay

**Comment by kr** [comment]
For whatever it's worth, I 100% agree with you. I think I was wrong to use that style.

**Comment by ysmolsky** [comment]
The main bulk of it was done, but the remains are to be fixed as we go. Closing
