### ISSUE TITLE
typedefs of ms, job and tube should not hide the pointer

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#458]
Make them similar to other typedefs (`Conn`, `Heap`). The code in question:
```
typedef struct ms     *ms;
typedef struct job    *job;
typedef struct tube   *tube;
typedef struct Conn   Conn;
typedef struct Heap   Heap;
typedef struct Jobrec Jobrec;
```

_Maybe, move each typedef next to the corresponding struct definition:_
```
typedef struct Heap   Heap;
struct Heap {
    size_t  cap;
    size_t  len;
    void    **data;
    Less    less;
    Record  rec;
};
```
_This may allow easier navigation to the struct definition from the referencing source code._

**Comment by kr** [comment]
> Maybe, move each typedef next to the corresponding struct definition

I tried to do this before. But some types have circular references to each other, so at least one of the typedefs can’t go next to its  struct definition. So I figured at least we can put all the typedefs together so it looks organized & tidy.

**Comment by ysmolsky** [comment]
@kr, thanks for saving time. Circular references were not on my mind.
