### ISSUE TITLE
cast between incompatible function types

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#472]
gcc8 on macos:

```
serv.c:29:20: error: cast between incompatible function types from 'void (*)(Conn *, int)' {aka 'void (*)(struct Conn *, int)'} to 'void (*)(void *, size_t)' {aka 'void (*)(void *, long unsigned int)'} [-Werror=cast-function-type]
     s->conns.rec = (Record)connrec;
                    ^
```

The type of `Serv.conns` is Heap while `connrec` sets `tickpos` to -1 for some reason. Needs further investigation.

**Comment by kr** [comment]
The `Record` function type is used by the binary heap to record the new positions of elements whenever they get moved or inserted. (Also I think "Record" is not a great name for this type, sorry.) The -1 value is probably coming from heapremove (which uses -1 to indicate the element has been removed).

Now that the compilers are being run in a more strict mode, it might be necessary to define connrec more like job_setheappos. Also see the comment on job_setheappos in dat.h.

**Comment by ysmolsky** [comment]
Thanks @kr, it looks like a good next step to me.
