### ISSUE TITLE
testing: cttest_close_frees_job fails on Linux

### ISSUE THREAD

**Issue by alanpost** [beanstalkd/beanstalkd#475]
Producing the following output, rather than succeeding.  A build against master last succeeded at Mon Jul 15 01:22:02 UTC 2019:

    ct/_ctcheck
    ........................F................................................

    cttest_close_frees_job: failure
    start server port=40517 pid=4338
    >28 reserve-with-timeout 1
    >29 put 0 0 100 1
    >29 a
    <29 INSERTED 1
    <28 RESERVED 1 1
    <28 a
    >29 stats-job 1
    <29 OK 149
    <29 ---
    id: 1
    tube: default
    state: reserved
    pri: 0
    age: 0
    delay: 0
    ttr: 100
    time-left: 99
    file: 0
    reserves: 1
    timeouts: 0
    releases: 0
    buries: 0
    kicks: 0

    >29 stats-job 1
    <29 OK 149
    <29 ---
    id: 1
    tube: default
    state: reserved
    pri: 0
    age: 0
    delay: 0
    ttr: 100
    time-left: 99
    file: 0
    reserves: 1
    timeouts: 0
    releases: 0
    buries: 0
    kicks: 0

    testserv.c:260: test: strstr(line, sub)
    testserv.c:260: "
    state: ready
    " not in "---
    id: 1
    tube: default
    state: reserved
    pri: 0
    age: 0
    delay: 0
    ttr: 100
    time-left: 99
    file: 0
    reserves: 1
    timeouts: 0
    releases: 0
    buries: 0
    kicks: 0

    "

    1 failures; 0 errors.
    make[1]: *** [check] Error 1

**Comment by ysmolsky** [comment]
What system are you running it on? What is the compiler version?

**Comment by alanpost** [comment]
This failure happened on CentOS 7, Ubuntu 14, and Ubuntu 16.  Which is every system I tried it on.  All amd64 with their respective system compilers.  In the case of CentOS 7 that's:

    $ gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

**Comment by ysmolsky** [comment]
@alanpost can you please try the tip master?

**Comment by ysmolsky** [comment]
I have just merged my guess at the issue.

**Comment by alanpost** [comment]
@ysmolsky The test suite passes again on the platforms I reported here.  Thank you for being so attentive, that was very fast.
