### ISSUE TITLE
move ignored coverage files from .travis.yml  to .codecov.yml

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#483]
Codecov uses .codecov.yml now: https://github.com/beanstalkd/beanstalkd/pull/482
We might want to move ignored files from travis to codecov config.

And we might want to enable status checks in codecov for the project with threshold ~10%, so that only big deep in coverage will result in the blocked merge.

https://docs.codecov.io/docs/commit-status

@sergeyklay

**Comment by sergeyklay** [comment]
I'll try to sort out ASAP. Thank you

**Comment by ysmolsky** [comment]
https://github.com/pingcap/tidb/blob/master/.codecov.yml
