### ISSUE TITLE
Chinese protocol wrong on peek cmd.

### ISSUE THREAD

**Issue by xpader** [beanstalkd/beanstalkd#485]
Peek command "All but the first operate only on the currently used tube." is wrong translate, in chinese translate "其中第一种形式的指令是针对当前使用的tube 格式" mean The first operate must on the currently used tube", but real mean is "All operate must on currently except first", so correct translate is "除了第一个，其它的操作只能在当前Tube。"。
@mickeyouyou

**Comment by mickeyouyou** [comment]
Please feel free to open a PR for fix it.

**Comment by ysmolsky** [comment]
PR's are more than welcome to fix the issue. _Pinkie-promise to merge them._ 🦄

**Comment by xpader** [comment]
#494 PR merged.
