### ISSUE TITLE
JSON format instead of Serialization

### ISSUE THREAD

**Issue by s4kibs4mi** [beanstalkd/beanstalkd#486]
It would be portable if beanstalkd publishes data in broker on JSON format instead of serialized data.

**Comment by ysmolsky** [comment]
@s4kibs4mi Can you clarify this?

**Comment by s4kibs4mi** [comment]
Lastly, when I checked I saw that job stays at broker as serialized,
ie :
```
`"O:23:\"App\\Jobs\\StatusJob\":8:{s:5:\"queue\";s:11:\"status\";s:29:\"\u0000App\\Jobs\\StatusJob\u0000data\";a:8:{s:7:\"id\";i:%d;s:9:\"d_id\";i:%d;s:8:\"r_id\";i:%d;s:6:\"status\";s:8:\"%s\";s:11:\"assigned_at\";i:%d;s:10:\"started_at\";i:%d;s:12:\"type\";i:%d;s:7:\"c_id\";i:%d;}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"`
```
Above is a job information in serialized state. Can't we make this json formatted ?
Let's say I am working on an environment were beanstalkd library isn't available. In this case, if job data is JSON formated I can easily make a payload and push to broker. Also, JSON formatted data is easy to read and understand than serialized data.

**Comment by ysmolsky** [comment]
beanstalkd is format agnostic. Every job is just a sequence of bytes. It is up to the client to interpret the contents of the job. So, I am not sure what is need to be fixed on beanstalkd side.
