### ISSUE TITLE
structs with flexible array member; that might be not safe

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#487]
For example, `tube` has `struct job buried` as last member, while `struct job` has `tube tube` embed in the middle. `struct jobs buried` means that this struct is embed, while `tube tube` means the pointer to the tube struct. This produces warnings if I try to compiler with `-pedantic`. Also it is hard to look and reason about this because I have to constantly think that `tube` is in fact a `*tube` (see #458).

As first step we need to fix #458 and maybe compiler will not warn anymore. If not, then we might need to rearrange the structures, however, this is not trivial. 

```
~/d/beanstalkd (master=) % make clean all CFLAGS="-std=gnu99 -Wextra -Wflexible-array-extensions"
rm -f vers.c  beanstalkd primes.o sd-daemon.o vers.o
cc -std=gnu99 -Wextra -Wflexible-array-extensions -Wall -Werror -Wformat=2 -g   -c -o darwin.o darwin.c
In file included from darwin.c:1:
./dat.h:205:16: error: 'buried' may not be nested in a struct due to flexible array member [-Werror,-Wflexible-array-extensions]
    struct job buried;
               ^
./dat.h:336:16: error: 'reserved_jobs' may not be nested in a struct due to flexible array member [-Werror,-Wflexible-array-extensions]
    struct job reserved_jobs; // linked list header
               ^
./dat.h:396:16: error: 'jlist' may not be nested in a struct due to flexible array member [-Werror,-Wflexible-array-extensions]
    struct job jlist; // jobs written in this file
               ^
3 errors generated.
make: *** [darwin.o] Error 1
```

**Comment by kr** [comment]
Ah, this arrangement was made under the assumption that it's okay to have a struct with a flexible array member as the last element in another struct. But looking at the standard I see that's not allowed, so it must be a gcc/clang extension.

I bet the easiest fix for this would be changing the last member of struct job, which is currently `char body[]`, to `char *body`, and adjusting the code accordingly. Hopefully this would have a negligible performance impact. (It might be important to allocate the job and body together in one malloc, but I *think* that would still be possible.)

**Comment by ysmolsky** [comment]
> Ah, this arrangement was made under the assumption that it's okay to have a struct with a flexible array member as the last element in another struct. But looking at the standard I see that's not allowed, so it must be a gcc/clang extension.

It is okay per standard. I have checked that because I was surprised by this error.

It is not okay to **embed struct with FAM** into another struct even as the last member.

**Comment by kr** [comment]
Yeah, that's what I was trying to describe. Sorry for the ambiguous language.

**Comment by ysmolsky** [comment]
Converting to *char has worked. compiler in pedantic mode is happy about structs in the PR.

 🎉
