### ISSUE TITLE
get rid of named variadic macros that is GNU extension

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#488]
Flag `-pedantic` leads to this error. I do not see how to eliminate this because macro is used  in two forms: `twarn("s")` and `twarn("s %s", a)`. C99 standard does not allow no arguments passed to the variable arguments, also it forbids the use of ## (which removes comma from macro when VA_ARGS is empty). 

It's a reminder, because I don't know if it makes sense to fix this at all.

```
./dat.h:209:24: error: named variadic macros are a GNU extension [-Werror,-Wvariadic-macros]
#define twarn(fmt, args...) warn("%s:%d in %s: " fmt, \
                       ^
./dat.h:211:25: error: named variadic macros are a GNU extension [-Werror,-Wvariadic-macros]
#define twarnx(fmt, args...) warnx("%s:%d in %s: " fmt, \
                        ^
```

**Comment by kr** [comment]
If it has to be fixed, maybe something like this would be palatable:

```c
#define twarnf(fmt, ...) warn("%s:%d in %s: " fmt, \
    __FILE__, __LINE__, __func__, __VA_ARGS__)
#define twarn(s) warn(%s:%d in %s: %s", \
    __FILE__, __LINE__, __func__, s)
```

And similarly for twarnx and twarnxf.

**Comment by ysmolsky** [comment]
Thanks, looks good. And one addition is that difference between `twarn` and `twarnx` is obscure. `twarn` should have been named `twarnerr` and `twarnx` as just `twarn`. I keep stuttering while reading this code. 

Will think more.

**Comment by kr** [comment]
The naming convention comes directly from the `err`, `errx`, `warn`, and `warnx` functions of the std lib. I just added a `t` on the front.

**Comment by ysmolsky** [comment]
Yes. All of those functions require some work. I plan to send a PR soon.

**Comment by ysmolsky** [comment]
First try was not successful. This requires more work and planning. Right now these macros are used for reporting errors in testing and writing errors to stderr, however that it is not capture most likely by parent program, except for docker, nor logging has timestamps attached to it. So this is better be reworked in conjunction with fixing logging... 🤷‍♂
