### ISSUE TITLE
Move the source code files into a src folder

### ISSUE THREAD

**Issue by silviucpp** [beanstalkd/beanstalkd#505]
Hello,

I think it's a good idea to move the source code files into a src folder and not keep them into the root folder where you have also other files like: license, readme, travis config, makefiles, etc.

Silviu

**Comment by ysmolsky** [comment]
What problem are you trying to solve?

**Comment by silviucpp** [comment]
It's not actual a problem. It's about organization of the source code aligned with a style used in most of the open source projects. For example go on github and select to see the trending C repositories for the last month. 

From the first 6 project all have the srouce code in a dedicated folder and in 5 of them  that folder is called "src"

Examples:
https://github.com/pjreddie/darknet
https://github.com/libuv/libuv
https://github.com/alibaba/tengine

Silviu

**Comment by ysmolsky** [comment]
I guess, I do not see this issue as critical for my workflow. Actually I prefer to have everything related to the project in the same directory because it's easier to navigate and work with files. This project is not so big compared to cited projects. I vote against moving sources in src for now.
