### ISSUE TITLE
beanstalkd does not exit on -TERM signal in Docker

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#527]
Something is off when beanstalkd is ran in docker container as first process.
```
% docker run -it --pid=container:bean --net=container:bean --cap-add sys_admin alpine sh
/ # kill -TERM 1
/ # kill -TERM 1
/ # kill -KILL 1
/ # kill -INT 1
/ # kill -HUP 1
/ #
```
I have attached strace. Notice that nothing happened for -KILL signal:
```
% docker run -t --pid=container:bean --net=container:bean --cap-add sys_admin --cap-add sys_ptrace strace
strace: Process 1 attached
epoll_pwait(6, 0x7ffff54d60dc, 1, 3600000, NULL, 8) = -1 EINTR (Interrupted system call)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=14, si_uid=0} ---
epoll_pwait(6, 0x7ffff54d60dc, 1, 3600000, NULL, 8) = -1 EINTR (Interrupted system call)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=14, si_uid=0} ---
epoll_pwait(6, 0x7ffff54d60dc, 1, 3600000, NULL, 8) = -1 EINTR (Interrupted system call)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=14, si_uid=0} ---
epoll_pwait(6, 0x7ffff54d60dc, 1, 3600000, NULL, 8) = -1 EINTR (Interrupted system call)
--- SIGHUP {si_signo=SIGHUP, si_code=SI_USER, si_pid=14, si_uid=0} ---
epoll_pwait(6,
```

Dockerfile that uses beanstalkd 1.10 build on alpine:
```
FROM alpine
RUN apk add --no-cache beanstalkd
RUN mkdir /beanstalkd
EXPOSE 11300
ENTRYPOINT ["/usr/bin/beanstalkd", "-z", "650000000"]
CMD ["-b", "/beanstalkd", "-f", "300"]
```
I have tried debian:jessie with the same result. So it is not Alpine linux.

The code where it happens:
```
    r = epoll_wait(epfd, &ev, 1, (int)(timeout/1000000));
    if (r == -1 && errno != EINTR) {
        twarn("epoll_wait");
        exit(1);
    }
```
It means that on regular clean Linux when I sent -TERM to the process return from epoll_wait never happens and process is immediately cleaned by OS. But on Docker the call returns and r==-1, errno=EINTR.

**Comment by ysmolsky** [comment]
This issue is critical. At this moment beanstalkd is killed with -KILL signal by Docker after timeout of (10?) seconds. This leads to slow restarts and praying that kill did not corrupt WAL file. _Ugh..._ And I wondered why restarts of beanstalkd containers are so slow. 😭

**Comment by GenaANTG** [comment]
@ysmolsky Hi! This problem is still exists. When we run beanstalk as PID1 in a container, he is not catching SITERM signal and still goes on.

**Comment by ysmolsky** [comment]
Uhm, v1.11 does not have this fix. You should try v1.12 for that.

**Comment by GenaANTG** [comment]
@ysmolsky Thanks a lot! I need to test it now.

**Comment by ysmolsky** [comment]
I will save you some time: do not bother. It is broken in v1.12 too. I have just tested and looking at the code I made a mistake of assuming that process can SIGKILL itself even if it has pid=1. But Linux blocks this as a feature.

**Comment by ysmolsky** [comment]
@GenaANTG you should try latest commit from master branch. It contains the fix.

**Comment by GenaANTG** [comment]
@ysmolsky Thanks a lot buddy!

**Comment by gypapp** [comment]
It seems (or seemed) to be a common problem with other software as well so another approach would be to install [tini](https://github.com/krallin/tini) or [dumb-init](https://github.com/Yelp/dumb-init) to cover this signal issue with PID 1.

I do not know if such tools exist would it be worth "patching" the beanstalk codebase.

**Comment by GenaANTG** [comment]
@ysmolsky Hi, mate! Is this bug is fixed in master branch? Looks like no. I have check your link above. In version 1.12 `kill -s SIGTERM` return 143 exit code. For docker needs we should have the way to stop beanstalkd with exit code 0. Do you have any sugesstions? Thanks.
