### ISSUE TITLE
set "-f 50" by the default and make -F not on by default

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#548]
The somewhat reliable way to run beanstalkd is to have "-f 0", fsync on every command. That means very bad performance. The default option "-F" - never fsync is a bad idea. If machine crashes user can lose everything since last time kernel flushed buffers instead of just couple of milliseconds of data.

Let's look at the benchmarks to get an idea of good default value for -f:

```
ctbench_put_delete_1024			    5000	    321840 ns/op	   4.83 MB/s
ctbench_put_delete_wal_1024_fsync_000ms	     100	  10783976 ns/op	   0.10 MB/s
ctbench_put_delete_wal_1024_fsync_050ms	    3000	    401186 ns/op	   3.01 MB/s
ctbench_put_delete_wal_1024_fsync_200ms	    3000	    372918 ns/op	   3.04 MB/s
ctbench_put_delete_wal_1024_no_fsync	    3000	    358677 ns/op	   3.05 MB/s

ctbench_put_delete_8192			    5000	    389117 ns/op	  37.42 MB/s
ctbench_put_delete_wal_8192_fsync_000ms	     200	   9642472 ns/op	   1.50 MB/s
ctbench_put_delete_wal_8192_fsync_050ms	    2000	    555952 ns/op	  16.20 MB/s
ctbench_put_delete_wal_8192_fsync_200ms	    2000	    524707 ns/op	  16.30 MB/s
ctbench_put_delete_wal_8192_no_fsync	    3000	    505258 ns/op	  23.37 MB/s
```

Performance degrades only for the fsync period -> zero. 50ms is a good enough tradeoff between performance and the amount of data lost in a powerloss crash.

We can measure performance for other -f values around the value of 50ms to get more accurate measurement. 

@beanstalkd/maintainers what do you think?

**Comment by kr** [comment]
Good analysis. I agree.
