### ISSUE TITLE
remove -n option as non functional and redundant

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#552]
There is no point to keep that option.

> -n option was only useful during development of the
compaction feature to compare its performance and disk
use to the older non-compacting behavior.
Which reminds me, we should remove that option now.
There's no reason for anyone to use it.
_Originally posted by @kr in https://github.com/beanstalkd/beanstalkd/issues/15#issuecomment-11368695_

**Comment by ysmolsky** [comment]
@tomponline @sergeyklay what do you think?

**Comment by tomponline** [comment]
Sounds reasonable to me
