### ISSUE TITLE
beanstalkd-win持久化功能怎么使用

### ISSUE THREAD

**Issue by wzlzking** [beanstalkd/beanstalkd#559]
请问这个版本支持持久化功能吗，我测试过好像没用，测试过程为先将一些 job 放到指定 tube 中，但先不消费 job，然后手动停止 beanstalkd 服务，再重新启动 beanstalkd 服务，然后执行消费 job 代码，但发现并没有将我之前放入的 job 进行消费，只会将我重启后新放入的 job 进行消费，不知道是不是我测试方法有问题，您可以帮忙解答一下吗？感谢！

**Comment by ysmolsky** [comment]
@wzlzking I think you meant to create issue in this repo: https://github.com/caidongyun/beanstalkd-win. Your questions is better be asked there, since beanstalkd does not support windows in this repo.
