### ISSUE TITLE
beanstalkd progress exit

### ISSUE THREAD

**Issue by pz9042** [beanstalkd/beanstalkd#565]
this morning I use command `sudo /usr/local/beanstalkd/bin/beanstalkd -b /data/beanstalkd -l 0.0.0.0 -p 11300 -u beanstalkd &` start service,but in afternoon，the progress exit. beanstalkd version is 1.11，os version is centos 7.6.1810. I not found any relate message in `/var/log/message`

**Comment by ysmolsky** [comment]
@pz9042 can you provide more details?

**Comment by ysmolsky** [comment]
By default beanstalkd writes into stderr and not to /var/log/messages. You might want to capture stderr.

**Comment by pz9042** [comment]
thanks,because i start service on backend,and not redirect stderr, I will provide  the error info tomorrow

**Comment by pz9042** [comment]
start command : `/usr/local/beanstalkd/bin/beanstalkd -b /data/beanstalkd -l 0.0.0.0 -p 11300 -u beanstalkd >/tmp/beanstalkd.txt 2>&1 &`
`[root@dev ~]# ps aux |grep -i  bean
root     20916  0.0  0.0 112724  1000 pts/0    S+   15:15   0:00 grep --color=auto -i bean
[root@dev ~]# ll /tmp/beanstalkd.txt 
-rw-r--r-- 1 root root 0 9月  16 10:21 /tmp/beanstalkd.txt
[root@dev ~]# 
`
there is no any message

**Comment by pz9042** [comment]
/usr/local/beanstalkd/bin/beanstalkd: prot.c:710 in check_err: read(): Connection reset by peer

**Comment by ysmolsky** [comment]
This is a normal message, it means that client's connection was lost during the read operation.
