### ISSUE TITLE
beanstalkd[2776] general protection ip:401f74 sp:7ffc346076d0 error:0 in beanstalkd[400000+e000]

### ISSUE THREAD

**Issue by jingwu15** [beanstalkd/beanstalkd#567]
beanstalk 1.10

the start cmd: 
beanstalkd -b /data/beanstalkd/binlog -F -z 65535000

the Error: 
beanstalkd[2776] general protection ip:401f74 sp:7ffc346076d0 error:0 in beanstalkd[400000+e000]

how to fixed the bug

**Comment by ysmolsky** [comment]
I am sorry, but that version was released long time ago and we do not support it anymore. Please use more recent release or even master branch to run this server.
