### ISSUE TITLE
Binlog files aren't deleted, no burried jobs

### ISSUE THREAD

**Issue by AndreC10002** [beanstalkd/beanstalkd#573]
We are running Beanstalkd 1.10 and notice that binlogs are never removed.  Found some chatter on mailing lists about buried or orphaned jobs holding logs, but that doesn't look like the problem here.

stats
OK 1015
---
current-jobs-urgent: 0
current-jobs-ready: 704251
current-jobs-reserved: 0
current-jobs-delayed: 12110
current-jobs-buried: 0
cmd-put: 5854200
cmd-peek: 0
cmd-peek-ready: 217273
cmd-peek-delayed: 5
cmd-peek-buried: 6
cmd-reserve: 0
cmd-reserve-with-timeout: 5356669
cmd-delete: 5572765
cmd-release: 0
cmd-use: 10736252
cmd-watch: 10736203
cmd-ignore: 10736203
cmd-bury: 0
cmd-kick: 0
cmd-touch: 0
cmd-stats: 6
cmd-stats-job: 5355479
cmd-stats-tube: 792
cmd-list-tubes: 216
cmd-list-tube-used: 1
cmd-list-tubes-watched: 10736204
cmd-pause-tube: 0
job-timeouts: 0
total-jobs: 5854200
max-job-size: 65535
current-tubes: 3
current-connections: 79
current-producers: 0
current-workers: 78
current-waiting: 13
total-connections: 10736323
pid: 24828
version: 1.10
rusage-utime: 2162.692000
rusage-stime: 4512.100000
uptime: 602319
binlog-oldest-index: 7244
binlog-current-index: 7517
binlog-records-migrated: 0
binlog-records-written: 11426859
binlog-max-size: 10485760
id: 6d64fabfedf95c49

And the tubes:

current-jobs-urgent: 0
current-jobs-ready: 0
current-jobs-reserved: 0
current-jobs-delayed: 12253
current-jobs-buried: 0
total-jobs: 4280032
current-using: 93
current-watching: 92
current-waiting: 18
cmd-delete: 4267779
cmd-pause-tube: 0
pause: 0
pause-time-left: 0

current-jobs-urgent: 0
current-jobs-ready: 704664
current-jobs-reserved: 0
current-jobs-delayed: 63
current-jobs-buried: 0
total-jobs: 625385
current-using: 0
current-watching: 0
current-waiting: 0
cmd-delete: 346924
cmd-pause-tube: 0
pause: 0
pause-time-left: 0

current-jobs-urgent: 0
current-jobs-ready: 0
current-jobs-reserved: 0
current-jobs-delayed: 0
current-jobs-buried: 0
total-jobs: 0
current-using: 0
current-watching: 1
current-waiting: 0
cmd-delete: 0
cmd-pause-tube: 0
pause: 0
pause-time-left: 0

It is keeping 280 binlogs that use 2.8GB of disk and don't shrink even after I manually removed 100.000 jobs from one of the queues.

Please let me know if you need additional information to further debug.

Thank you.

**Comment by AndreC10002** [comment]
Note that I believe the value:

binlog-oldest-index: 7244

reflects the fact that I deleted binlogs manually many times in the past to free space (and to remove old jobs).

**Comment by HenriNijborg** [comment]
Duplicate of https://github.com/beanstalkd/beanstalkd/issues/570 ?

**Comment by AndreC10002** [comment]
I guess so.  Sorry, didn't find that one somehow.  Will try 1.11 and see what happens.
Thanks for letting me know about that ticket.
