### ISSUE TITLE
prot.c:710 in check_err: read(): Connection reset by peer

### ISSUE THREAD

**Issue by StevenFlecha** [beanstalkd/beanstalkd#578]
In our kubernetes cluster we have 3 BE services (hosted on GCP).

We have 1 instance of Beanstalkd service & 1 ES cluster (3 master pods, 2 data pods, 2 client pods). Each BE app has its own Redis instance and Mysql server.

Now we built various health checks and we regularly see (like 5-10 times a day) connection speed issues. In the health check all we do is connect to the service and check how long this takes (via php) and if it takes too long (or doesn't connect at all) we raise a flag.

We see results like:

```
Test took 10.616209983826 sec at 2020-04-28 23:45:11.
Environment: production
Test took too long - more than 2 seconds.
Checked items and their timing:
pdo took 0.0043079853057861 seconds
beanstalkd took 10.036059141159 seconds
redis took 0.0028140544891357 seconds
ElasticSeearch took 0.57300901412964 seconds
```

The connection time to beanstalkd goes up to 20+ seconds.

```
$startbeanstalkd = microtime(true);
// connect to Beanstalkd
try {
    $queue = new Beanstalk(
        [
            'host' => $config->beanstalkd->host,
            'port' => $config->beanstalkd->port
        ]
    );
    $queue->connect();
} catch (\Exception $e) {
    $testPassed = false;
    $testResult['Beanstalkd']['status'] = false;
    $testResult['Beanstalkd']['message'] = $e->getMessage();
    $testResult['Beanstalkd']['connectionDetails'] = json_encode($config->beanstalkd);
}
if($testPassed) $queue->disconnect();
$beantime = microtime(true);
$timetrack['beanstalkd'] = $beantime - $startbeanstalkd;
```
We noticed this error from beanstalkd regulary:

/usr/bin/beanstalkd: prot.c:710 in check_err: read(): Connection reset by peer
But searching on this hasn't really given us much info.

Not really relevant I think but we use Rancher 2 to manage our clusters.

First I'd love to know what the beanstalkd error means and how to solve it

Then secondly would love to hear any suggestion on the general sockets time out / are slow-as-shit problem.

Thank you!

**Comment by ysmolsky** [comment]
The error you see in beanstalkd is not the error indicating some flaw, but rather saying that client (peer) was disconnected unexpectedly, meaning that client has closed the socket without saying goodbye.

The client code you posted measuring not only connection time, but also includes "disconnect" time. I have no idea about implementation of the client lib you used. 

Also there might be an issue with PHP server itself, or network lag between php instance and beanstalkd. Are you sure that network is reliable? Are you sure that pod running beanstalkd not getting evicted regularly? all this adds up...

This is all I can give for now.
