### ISSUE TITLE
Can not run beanstalkd 1.11 but 1.10 is ok!

### ISSUE THREAD

**Issue by GDdark** [beanstalkd/beanstalkd#580]
![image](https://user-images.githubusercontent.com/15982894/83347078-e0a96680-a354-11ea-9286-9044f5c8c4c6.png)

System version: Ubuntu 18.04

**Comment by ysmolsky** [comment]
Thank you for reporting this. I cannot reproduce this in the current debian, though. Can you try to compile the latest version from master and verify that it happens there as well? We have changed this code after 1.11. Do you run this on the existing data or is data dir empty?

**Comment by GDdark** [comment]
Yes. The data dir is empty!
I compile the latest version from master and it's work!!!
Thank you!

**Comment by ysmolsky** [comment]
I am glad that it has resolved for you. I still wonder what kind of error you encountered there. I will keep this issue open for a while.

**Comment by ysmolsky** [comment]
@GDdark do you plan to investigate why 1.11 is broken for you so I can replicate the problem and fix it probably? I could not replicate this on my own machines even using ubuntu 18.04. Maybe it's something else causing this problem...

**Comment by GDdark** [comment]
There's still a problem with my machine! 
I tried to give /data/beanstalkd 777 permissions and still not work!
My environment is not a pure linux machine!!!
I used vagrant to initialize the Ubuntu 18.04 environment in macos.
I hope it is helpful for you!!

**Comment by GDdark** [comment]
I tried to touch a file named binlog.1 and gave it 777 permissions
And still not work!

![image](https://user-images.githubusercontent.com/15982894/83989580-6fcc0500-a979-11ea-829f-30ce7387526b.png)

**Comment by ysmolsky** [comment]
Interesting, it may be related to the way vagrant was setup. Or file permissions (not likely). Can you run `stat /data/beanstalkd` and `stat /data/beanstalkd/binlog.1` and paste results here?

**Comment by GDdark** [comment]
Sure!
![image](https://user-images.githubusercontent.com/15982894/84738675-ec478f00-afdc-11ea-9282-390fd1886380.png)

there is no file named binlog.1 in /data/beanstalkd 
I think beanstalkd create binlog.1 failed

**Comment by ysmolsky** [comment]
I guess that something is wrong with vagrant or the context you run it in. I do not see anything related to beanstalkd itself.
