### ISSUE TITLE
Automated dockerhub builds

### ISSUE THREAD

**Issue by SamMousa** [beanstalkd/beanstalkd#589]
Now that there is a `Dockerfile` in the repo it would be nice to add an automated build to dockerhub.

The setup process for that is fairly simple and should take at most ~10 mins, it has to be done by a repo admin though.

**Comment by SamMousa** [comment]
Is this planned or will beanstalkd not have official images on DockerHub?

**Comment by ysmolsky** [comment]
This is not planned by me. I cannot say that for others though.

**Comment by SamMousa** [comment]
I'm up for helping out with this, but at some point someone with more access needs to be involved.

Things I can do:

- [ ] Set up Github Action to build the edge image on pushes to master
- [ ] Set up Github Action to build a tagged release when a new tag is pushed
- [ ] Update the :latest  tag in docker with the latest tagged release

Things I cannot do due to lack of permissions: 

- Create dockerhub organisation for beanstalkd
- Create API token for dockerhub
- Configure CI secret in github so that CI can login to docker.

I'm happy to help out, this should take only around ~20 minutes after which every push to master will build an image and push it to dockerhub.

**Comment by githubjeka** [comment]
🙏🏻 I would like to get the official version too

@SamMousa would be nice if you use https://github.com/marketplace/actions/fork-sync and update https://hub.docker.com/r/sammousa/beanstalkd and setting your actions.

I would love to use this script to get beanstalkd in dockerhub .

Others hubs are oldest or used `git clone` in containers
https://hub.docker.com/search?q=beanstalkd&type=image&sort=updated_at&order=desc

**Comment by SamMousa** [comment]
Mine is not an official one, but could indeed do something like that.

**Comment by SamMousa** [comment]
Is there any interest from maintainers to set this up? As said, I'm happy to help but some steps need to be done by people with appropriate permissions.

**Comment by SamMousa** [comment]
Fixed by #613.

In the meanwhile I'm building new builds automatically here: [ghcr.io/sammousa/beanstalkd:latest](https://github.com/sammousa/beanstalkd/pkgs/container/beanstalkd)

Note this branch is not auto synced (yet) but I intend to keep it reasonably close to `master`.
