### ISSUE TITLE
wish add batch put and batch reserve features

### ISSUE THREAD

**Issue by ikool-cn** [beanstalkd/beanstalkd#627]
wish add batch put and batch reserve features

thanks!

**Comment by ysmolsky** [comment]
If you want to have a feature added, you are more than welcome to write the protocol description for it and then we can discuss it. Also I have rather limited time dedicated to this project. So implementation is up to contributors. Unless my employee is interested in this particular feature and asks me to do it...

**Comment by SamMousa** [comment]
I don't get why these batch operations are needed. In my opinion batching makes everything complicated.
It requires a way to do atomic batch operations or partial batch operations which complicates both client and server code.

What we do in our systems is a fanout approach where our synchronous code (that runs in context of a web request) puts the minimum information for the batch in a job. The handler for that job than inserts jobs for each of the individual tasks.

I'm unclear what exact issue this solves and at what scale it is required.

**Comment by SamMousa** [comment]
This was not implemented right? Since you closed it as completed that might be confusing
