### ISSUE TITLE
Suggested way to set Beanstalk UNIX domain socket permissions

### ISSUE THREAD

**Issue by cooldarkdryplace** [beanstalkd/beanstalkd#629]
Hi, I am running beanstalkd on Debian as a systemd service. It is installed via apt-get. 
My only adjustment was to edit `/etc/default/beanstalkd ` to listen on UDS: `/etc/init.d/beanstalkd`.
```
## Defaults for the beanstalkd init script, /etc/init.d/beanstalkd on
## Debian systems.

BEANSTALKD_LISTEN_ADDR=unix:///tmp/beanstalkd.sock
BEANSTALKD_LISTEN_PORT=11300

# You can use BEANSTALKD_EXTRA to pass additional options. See beanstalkd(1)
# for a list of the available options. Uncomment the following line for
# persistent job storage.
BEANSTALKD_EXTRA="-b /var/lib/beanstalkd"
```

This config creates UDS:
```
srwxr-xr-x 1 beanstalkd beanstalkd    0 Oct 23 06:46 beanstalkd.sock
```

According to [the doc](https://man7.org/linux/man-pages/man7/unix.7.html), connecting to the socket requires read-write permissions.

Question: what is the suggested way to adjust UNIX domain socket permissions?

I can use `chmod` to update permissions right after service starts, but I was wondering if a configuration parameter can help me avoid this step. 

The preferable way would be to keep the original systemd unit and only set permissions via beanstalkd defaults so that it survives package updates.

**Comment by ptjm** [comment]
set umask before starting beanstalkd.

umask 007 will give srwxsrwx---

**Comment by cooldarkdryplace** [comment]
Thanks, @ptjm! This is precisely what I need.
