### ISSUE TITLE
Allow delete job from another connection

### ISSUE THREAD

**Issue by iseki0** [beanstalkd/beanstalkd#644]
I read the thread ["Deadline soon explained"](https://groups.google.com/g/beanstalk-talk/c/Iy0MrFvr4w8). Why beanstalk doesn't support delete job from another connection? Does it a more clean way to avoid the problems that described in the thread?
In current protocol, if a reserved job close to timeout, the client will fall in a busy-poll-like state. It's a unnecessary cost in communication.

**Comment by ptjm** [comment]
Until the connection is dropped or the ttr is reached, the job belongs to the connection that reserved it. The appropriate action in response to a deadline soon is to deal with it. e.g., you can make sure it's still being processed and touch it to push the deadline out, or you can stop processing it and release or delete it. You only end up polling if you choose to ignore it.

If one worker is in the middle of processing a job and still within the ttr and another worker can delete it, the result won't exactly be clean. Similarly, if the worker keeps processing beyond the ttr, you can end up with the job being processed twice. You need to pay attention to the ttr.

**Comment by iseki0** [comment]
I also afraid the 1 second safe-margin is not enough.
