### ISSUE TITLE
intermittent protocol errors

### ISSUE THREAD

**Issue by kr** [beanstalkd/beanstalkd#83]
https://groups.google.com/d/topic/beanstalk-talk/MbcHPrVJtSw

We've also seen something similar at Heroku. It's difficult to reproduce,
so consequently difficult to fix.

**Comment by jevgenijsb** [comment]
```
echo -e "use some_tub e\r\n" | nc beanstalk-docker 11300
UNKNOWN_COMMAND
USING some_tube
```
